### ISSUE TITLE
Is there any way to make route().current() also match params?

### ISSUE THREAD

**Issue by mikemand** [tighten/ziggy#211]
### Expected Behavior
Some way to determine that the route matches, including params. For example, if I'm on any of the following pages, `route().current('backend.inventory.show')` returns true because the route name is the same for all:
* /backend/inventory/1/category/2
* /backend/inventory/2/category/2
* /backend/inventory/3/category/13
* /backend/inventory/7/category/1
* /backend/inventory/1/category/13

### Current Behavior
I'm not sure if there is already some method or argument to a method that will allow me to determine this.

### Currently installed Laravel version:
`5.8.15`

### Currently installed Ziggy version
`0.7.1`

### Example route from your Laravel Routes file.
```php
Route::get('/backend/inventory/{tenant}/category/{category}', [Backend\InventoryController::class, 'show'])->name('backend.inventory.show');
```
### Contents of Ziggy.namedRoutes
```json
"backend.inventory.show": {
	"domain": null,
	"methods": [
		"GET",
		"HEAD"
	],
	"uri": "backend/inventory/{tenant}/category/{category}"
}
```

### Ziggy call in context
I have a custom Vue directive that uses the `href` attribute to determine if the link is to the current page. The link's `href` will be a route: `<a :href="route('backend.inventory.show'. { tenant: currentTenant, category: category.id })">{{ category.name }}</a>`

```javascript
export default function (el, binding, vNode) {
    let { name } = vNode.data.attrs.href;

    if (name === undefined) {
        return;
    }

    // You can ignore this part, it works as intended for those routes that I DO want to be fuzzy matched.
    if (binding.modifiers.fuzzy) {
        const parts = name.split('.');

        if (parts.length > 1) {
            parts.splice(-1, 1, '*'); // remove last segment of route and replace with fuzzy token
            name = parts.join('.');
        }
    }

    if (route().current(name)) {
        el.classList.add('active');
    }
}
```

**Comment by DanielCoulbourne** [comment]
This is a good idea. I mayyyyy have time for it tomorrow, but I can't be sure and if not it will be a couple weeks.

**Comment by m1guelpf** [comment]
@DanielCoulbourne Sorry to bother you, but is there any progress on this? :D

**Comment by TheNewSound** [comment]
I would like to see that `current()` wont return a name but the whole route object, including resolved parameters

**Example:**
Route: `/item/{name}`
Current url: _/item/example_
So I could use `current().parameters` to get: {name: example}

**Comment by reinink** [comment]
I just ran into this myself. It would be awesome if Ziggy handled this out of the box! 👌

**Comment by bakerkretzmar** [comment]
@TheNewSound interesting idea, can you make a new issue for that feature specifically?

**Comment by bakerkretzmar** [comment]
This was added in #330 and will be available in v1 💪🏻

**Comment by mikemand** [comment]
That's so awesome! Thank you @bakerkretzmar. Also, hurray for `1.0` release!
