### ISSUE TITLE
How can I use Ziggy with React and Inertia ?

### ISSUE THREAD

**Issue by gregoryalary** [tighten/ziggy#326]
How can I call in a React component the JavaScript `route` function generated by the Ziggy's `@route` directive ?

The `route` function is generated at runtime so it's impossible to import it beforehand in the react component and therefore, Laravel Mix throws an error and can't compile the project.

My stack is Laravel 8, Inertia & React.

Thanks !

**Comment by bakerkretzmar** [comment]
You can import the `route()` function either from Ziggy's vendor directory, with something like

```js
resolve: {
    alias: {
        ziggy: path.resolve('vendor/tightenco/ziggy/src/js/route.js'),
    },
}
```

added to your Webpack config, or by installing the `ziggy-js` npm package.

Ziggy provides an artisan command, `php artisan ziggy:generate`, that will generate the object with all of your route information and put it either at `resources/assets/js/ziggy.js` or at the path you pass it.

After doing those two things, you should be able to just

```js
import route from 'ziggy'; // or `ziggy-js` if you use the npm package
import Ziggy from './ziggy'; // path to the file generated by the artisan command
```

and use `route()` normally.

Take a look at the [Artisan Command](https://github.com/tighten/ziggy#artisan-command) section in the readme too.

I'm going to close this but let me know if that works and if you have any other questions!

**Comment by gregoryalary** [comment]
Thanks, it worked ! 

Do you think it's good idea to add this information to the doc ?

**Comment by bakerkretzmar** [comment]
Yep! The alias part is [already there](https://github.com/tighten/ziggy#artisan-command), but it could definitely be clearer and it's worth mentioning React in addition to Vue.

**Comment by bakerkretzmar** [comment]
@caturandi-labs https://vitejs.dev/config/#resolve-alias
