### ISSUE TITLE
Don't check domain value at route().current()

### ISSUE THREAD

**Issue by nevmerzhitsky** [tighten/ziggy#329]
### Description

I'm developing a Laravel 8 project locally and can access it via both (and many more) `localhost` and `blahblah.test` domains. I configured Laravel's `APP_URL` as "http://blahblah.test". And ran `@php artisan ziggy:generate "resources/js/ziggy.js"` via Composer `post-autoload-dump` script. Well, when I open the site at http://blahblah.test/ I see the correct work of `route().current('dashboard')` (I have this named route and it exists in `resources/js/ziggy.js`). But when I open http://localhost/ - the function doesn't work properly (with any named route). If I set `APP_URL` to "http://localhost/", the result is mirrored: works for http://localhost/ and not for http://blahblah.test/.

I should note that I use your library in VueJS environment.

### Suggestion

I propose to don't include domain proto, name, and port to the algorithm of `route().current()` to give an ability of this function to work on deployment with a lot of different domains which point to the same back-end.

### Alternatives

Idk

**Comment by jakebathman** [comment]
I'm reviewing a PR right now that would change how `route().current()` would work, so let me see if we can at the very least provide some flexibility with how it matches the path/query versus the entire URL. I could see that kind of flexibility coming in handy (and reducing issues like you've had).

**Comment by bakerkretzmar** [comment]
@nevmerzhitsky interesting idea, thanks!

Are there any situations where you think this would be useful besides when switching domains locally as you described? If you run `php artisan ziggy:generate` during deployment, won't your frontend always have the correct `APP_URL`? Thanks!

**Comment by nevmerzhitsky** [comment]
> @nevmerzhitsky interesting idea, thanks!
> 
> Are there any situations where you think this would be useful besides when switching domains locally as you described? If you run `php artisan ziggy:generate` during deployment, won't your frontend always have the correct `APP_URL`? Thanks!

Yep, deployment in one domain environment works fine. But projects like a platform of landing pages (multiple websites managed by one back-end) will feel this issue.

**Comment by bakerkretzmar** [comment]
@nevmerzhitsky when you have a minute can you provide a more detailed example of the setup you have in mind to help us work on this?

We can't remove the domain check entirely because there might be parameters there—if a route definition looks something like `{team}.app.com/users/{user}` we can't just match on `/users/{user}`. The protocol we can probably drop completely, and we could certainly put this behind a flag or configuration option, but I want to understand it better.

We could also make the third parameter to `route()`, `absolute`, apply to `current()` as well, so that calling `route(undefined, undefined, false).current(...)` only looks at the pathname. That's a bit verbose but it would be simple to implement.

Do you actually have an app where `APP_URL` isn't defined? How does your frontend communicate with Laravel currently? In the platform of landing pages scenario, are all the individual landing pages on different base domains _and_ also using Ziggy directly?

Thanks!

**Comment by nevmerzhitsky** [comment]
> @nevmerzhitsky when you have a minute can you provide a more detailed example of the setup you have in mind to help us work on this?
> 
> We can't remove the domain check entirely because there might be parameters there—if a route definition looks something like `{team}.app.com/users/{user}` we can't just match on `/users/{user}`. The protocol we can probably drop completely, and we could certainly put this behind a flag or configuration option, but I want to understand it better.
> 
> We could also make the third parameter to `route()`, `absolute`, apply to `current()` as well, so that calling `route(undefined, undefined, false).current(...)` only looks at the pathname. That's a bit verbose but it would be simple to implement.
> 
> Do you actually have an app where `APP_URL` isn't defined? How does your frontend communicate with Laravel currently? In the platform of landing pages scenario, are all the individual landing pages on different base domains _and_ also using Ziggy directly?

In the current project, I use InertiaJS, VueJS, etc from Laravel Jetstream and I set `APP_ENV` and have no unsolvable issues with the library. And I have no experience in the development of landing platform, it was just an abstract idea. Thus I cannot advocate it. Let's forget the idea.

I think it will be great if it will work as you proposed: via the parameter.

**Comment by nevmerzhitsky** [comment]
Just one comment about the solution.

I use the library with non-absolute routes in Vue by this wrapper:

```js
Vue.mixin({
    methods: {
        '$route': (name, params, absolute) => {
            absolute = typeof absolute === 'undefined' ? false : absolute
            return route(name, params, absolute, Ziggy)
        },
    }
})
```

If you implement the proposed solution I will add this wrapper too:

```js
Vue.mixin({
    methods: {
        '$currentRoute': (name, absolute) => {
            absolute = typeof absolute === 'undefined' ? false : absolute
            return route(undefined, undefined, absolute, Ziggy).current(name)
        },
    }
})
```

Could you consider breaking the relationship between `current()` and `Router` class?

And also make a way to configure the default value of `absolute` argument globally or per "JS-app"? I just annoying to do things like `absolute = typeof absolute === 'undefined' ? false : absolute`.

**Comment by bakerkretzmar** [comment]
@nevmerzhitsky thanks a lot for this additional context! I'll look into adding this functionality via the parameter.

Both of those other suggestions, extracting `current()` somehow and overriding configuration globally per-app, are great ideas. I'll explore what they might look like.

Also, I think you can shorten your `absolute` check by setting its default value to `true`:

```js
```

**Comment by joseph-d** [comment]
I am experiencing a similar issue to this, but between `http://testsite.local` and `http://testsite.local:3000` -- in other words, when I am using Browsersync which usually uses port 3000.

Would the issue I am experiencing be covered by what is being discussed in this issue, or should I open up a separate issue and describe things in more detail?

**Comment by bakerkretzmar** [comment]
@joseph-d pretty sure this would cover it. Does using `route(undefined, undefined, false)` solve that for you?

Closing this issue because the above workarounds do the trick for now. We're exploring some more convenient ways to configure this in the future.

**Comment by joseph-d** [comment]
@bakerkretzmar Thanks, yes, it's actually working properly for me since v1 now.

**Comment by Sammyjo20** [comment]
We're experiencing issues with Ziggy falling over if we pass a parameter into a `Route::domain()`. E.g: `Route::domain('{companyDomain}')->group(function () {})` and we keep getting "Required parameter "companyDomain" doesn't exist." It's very frustrating!

**Comment by bakerkretzmar** [comment]
@Sammyjo20 please open a new issue with all the details and we'll be happy to help.

**Comment by Sammyjo20** [comment]
Cheers @bakerkretzmar!

**Comment by Tofandel** [comment]
@Sammyjo20 Did you open an issue about Route::domain('{companyDomain}') ? As I'm having the same issue, I'm trying to setup subdomains routes but they don't appear in the generated file

**Comment by fabioselau077** [comment]
> We're experiencing issues with Ziggy falling over if we pass a parameter into a `Route::domain()`. E.g: `Route::domain('{companyDomain}')->group(function () {})` and we keep getting "Required parameter "companyDomain" doesn't exist." on our front-end. It's very frustrating!

same here... any solution?

**Comment by bakerkretzmar** [comment]
`Required parameter "companyDomain" doesn't exist.` doesn't look like any of the error messages that Ziggy might produce, but please open a detailed issue if you think this is a problem with Ziggy.
