### ISSUE TITLE
params get replaced by [params.id] when they shouldn't

### ISSUE THREAD

**Issue by briska** [tighten/ziggy#335]
Hello, I tried to pass some params to route function, but they were ignored. So i was trying to understand why and found this piece of code:

```js
if (
    params.hasOwnProperty('id') &&
    this.template.indexOf('{id}') == -1
) {
    params = [params.id];
}
```

In my route template i have `{id?}` instead of just `{id}`, so the condition `this.template.indexOf('{id}') == -1` evaluates as `true` and that means all my params get replaced by just `[params.id]`.

I don't know, if that's something important for you and for this package. For now I'm gonna make some workaround, that will work for me. I just wanted to let you know... and to say thanks for great package 👍

**Comment by bakerkretzmar** [comment]
@briska this was fixed a while ago but the fix has not been released yet, technically it's a breaking change so it's going to be in `1.0`. Hopefully that release will be out some time in the next few weeks. Thanks for your patience!
