### ISSUE TITLE
Subdomain not getting picked up

### ISSUE THREAD

**Issue by bryanjamesmiller** [tighten/ziggy#348]
Hi, thanks for this package! When using the Spatie multi-tenancy package, I am having the following issue.

### Expected behavior

When I am on a tenant URL, such as `http://tenant-one.my-app.test/comment` that has the named route `comment.index` and I try using `this.route().current('comment.index');` in a Vue component I should get a result of `true`.  However, I get `false`.

Similarly, when I am on the same URL and I try using `this.route().current()` in a Vue component I would expect to get the named route `comment.index` as the result.  However, I get `undefined`, probably due to the above.

### Versions

- **Laravel**: 8.12.3
- **Ziggy**: 0.9.4 (composer) and also "ziggy-js": "^0.9.4" (packagist)
"spatie/laravel-multitenancy": 1.6.9

**Comment by bakerkretzmar** [comment]
Can you please share the route definition, the relevant section of the output of `Ziggy.namedRoutes` in your console, and the context you're making those `route()` calls in? Do you have other routes or uses of Ziggy that _are_ working as expected? Thanks.

**Comment by bryanjamesmiller** [comment]
Hi @bakerkretzmar - thanks for the quick response.

This is working as expected:  `this.route('comment.index', [], false);` as it results in creating the route `/comment`.  

My route is:
```
Route::middleware('tenant')->group(function () {
    Route::middleware('auth')->group(function () {
        Route::resource('comment', CommentController::class)->only([
            'index', 'show',
        ]);
    });
```

When I try `Ziggy.namedRoutes` in my console, I get `Ziggy is not defined.` I also tried console.logging the following from within my Vue component with no luck:

```
            console.log(Ziggy.namedRoutes);
            console.log(this.Ziggy.namedRoutes);
            console.log(this.route().namedRoutes);
            console.log(this.namedRoutes);
```

**Comment by bakerkretzmar** [comment]
Interesting. My understanding of `Route::resource()` is that it names routes using the plural, so I would have expected `route('comments.index')` to work, but _not_ `route('comment.index')`.

Is `this.route('comment.index', [], false);` inside the template of a Vue component, not a method call or mounted hook or something?

How are you setting `this.route`? Do you have a global mixin in app.js like `Vue.mixin({ methods: { route: route } })`?

**Comment by bryanjamesmiller** [comment]
Hi @bakerkretzmar thanks again for the quick response.  Here are my answers to your questions:

1) When I run `php artisan route:list` I see `comment.index` for the route name.

2) I have `this.route('comment.index', [], false);` inside a regular computed property in a .vue file/component:

```
    computed: {
        getIndexRoute () {
            return this.route('comment.index', [], false);
        },
```

3) I am pulling in the package in app.js like this:

```
import route from 'ziggy';
import { Ziggy } from './ziggy';

require('./bootstrap');

window.Vue = require('vue');

Vue.mixin({
    methods: {
        route: (name, params, absolute) => { return route(name, params, absolute, Ziggy); }
    }
});
```

Nothing much going on inside `./bootstrap`:

```
window._ = require('lodash');
window.axios = require('axios');
window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
```

webpack.mix.js:

```
const mix = require('laravel-mix');
const path = require('path');

mix
    .webpackConfig({
        resolve: {
            alias: {
                ziggy: path.resolve('vendor/tightenco/ziggy/src/js/route.js')
            }
        }
    })
    .js('resources/js/app.js', 'public/js')
    .extract()
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('tailwindcss'),
        require('postcss-nested'),
        require('autoprefixer')
    ]);

if (mix.inProduction()) {
    mix
        .version();
}
```

and I am not pulling in `@routes` in Blade anywhere - I actually tried using `@routes` before installing npm, and unfortunately I was having separate issues with that where it wasn't cooperating with Vue for some reason, so then I started down this road instead as it seemed potentially better anyways to just pull it in via JS instead of blade.

**Comment by bakerkretzmar** [comment]
@bryanjamesmiller okay, thanks a lot for these details!

Did you run `php artisan ziggy:generate`, and the output of that file is in a file called `ziggy.js` right beside your `app.js`? `namedRoutes` should be in there, can you share the value of the `comment.index` entry in that object?

**Comment by bryanjamesmiller** [comment]
@bakerkretzmar yes, I had run the artisan command and the resulting file `ziggy.js` was placed in the same directory as `app.js`.  Here is the `comment.index` entry:

`["GET","HEAD"],"domain":null},"comment.index":{"uri":"comment","methods":`

**Comment by bakerkretzmar** [comment]
Okay sorry, can you share more of that file actually? Or at least all the top-level keys like `baseDomain` and `baseUrl`, and a couple other routes?

My current best guess is that your routes are only being generated for the "current" tenant at the moment you run the `php artisan ziggy:generate` command, but I want to look into this more.

**Comment by bryanjamesmiller** [comment]
```
        namedRoutes: {"debugbar.openhandler":{"uri":"_debugbar\/open","methods":["GET","HEAD"],"domain":null},"debugbar.clockwork":{"uri":"_debugbar\/clockwork\/{id}","methods":["GET","HEAD"],"domain":null},"debugbar.telescope":{"uri":"_debugbar\/telescope\/{id}","methods":["GET","HEAD"],"domain":null},"debugbar.assets.css":{"uri":"_debugbar\/assets\/stylesheets","methods":["GET","HEAD"],"domain":null},"debugbar.assets.js":{"uri":"_debugbar\/assets\/javascript","methods":["GET","HEAD"],"domain":null},"debugbar.cache.delete":{"uri":"_debugbar\/cache\/{key}\/{tags?}","methods":["DELETE"],"domain":null},"welcome":{"uri":"\/","methods":["GET","HEAD"],"domain":null},"login":{"uri":"login","methods":["GET","HEAD"],"domain":null},"logout":{"uri":"logout","methods":["POST"],"domain":null},"register":{"uri":"register","methods":["GET","HEAD"],"domain":null},"password.request":{"uri":"password\/reset","methods":["GET","HEAD"],"domain":null},"password.email":{"uri":"password\/email","methods":["POST"],"domain":null},"password.reset":{"uri":"password\/reset\/{token}","methods":["GET","HEAD"],"domain":null},"password.update":{"uri":"password\/reset","methods":["POST"],"domain":null},"password.confirm":{"uri":"password\/confirm","methods":["GET","HEAD"],"domain":null},"comment.index":{"uri":"comment","methods":["GET","HEAD"],"domain":null},"comment.show":{"uri":"comment\/{comment}","methods":["GET","HEAD"],"domain":null}},
        baseUrl: 'http://my-app.test/',
        baseProtocol: 'http',
        baseDomain: 'my-app.test',
        basePort: false,
        defaultParameters: []
    };
```

**Comment by bakerkretzmar** [comment]
@davejamesmiller thanks for your patience. Here's the quick fix—update your `app.js` to this:

```js
Vue.mixin({
    methods: {
        route: (name, params, absolute) => {
            return route(name, params, absolute, {
                ...Ziggy,
                baseUrl: window.location.origin,
                baseDomain: window.location.host,
            });
        }
    }
});
```

The behaviour you're seeing is being caused by Spatie's multi-tenancy package not playing super nicely with the same part of Ziggy that #334 took issue with—the fact that we use `url('/')` to determine the base URL for Ziggy's route generation.

The `@routes` Blade directive works fine for your use case: it gets its base URL late in the current HTTP request **when there is already a tenant**, so it correctly passes `http://tenant-one.my-app.test/` back to Ziggy's Javascript, which works because that is indeed the current window's URL.

The `ziggy:generate` Artisan command, however, runs without an HTTP request and therefore does **not** have a tenant set up—its 'URL' is set automatically to the value of `APP_URL`, which is `http://my-app.test`, and so later when you try to use it in your app, it doesn't match the current window URL.

The change in #334 means that `@routes` will actually also stop working for this specific setup in Ziggy v1. I'm not sure how I feel about this... Spatie's multi-tenancy package configures the tenant and sets it in the URL without adjusting the route definition, which took me a while to figure out and get working and feels kinda weird to me. If the tenant was a real route parameter, set up with something like `Route::domain('{tenant}.my-app.test')...`, none of this would be an issue.

Ignoring the domain when calling `route().current()`, as suggested in #329, would also solve this issue. I still don't like that being the default behaviour, but now I'm not quite so sure.

Thoughts?

**Comment by bryanjamesmiller** [comment]
@bakerkretzmar I will try this out shortly, but it makes perfect sense and looks very promising.  Thank you for your help on this!

Regarding the `@routes` blade directive, while that at first was working for me (before I started using the npm package), I think the problem I was running into had to do with testing a view that was compiled by Vue.  It was a simple "assertSee('some text')" view.  It appeared that phpunit couldn't get past the compiled results of the @routes directive.  However, you have given me what looks like a working path forwards, so I myself will probably not need a solution for that anymore, but just as a heads up if you wanted to know what happened with my attempts at that approach.

**Comment by bakerkretzmar** [comment]
@bryanjamesmiller sounds good! That PHPUnit issue is interesting.... do you remember the specifics of the errors you were seeing? I've made similar text/content assertions on views with `@routes` before without issue, I'm not totally sure about Vue but I'm curious how that could affect it since PHPUnit of course can't execute the JS.

**Comment by aboshehabehab** [comment]
@bakerkretzmar Hi, Did you guys managed to find a solution for this issue ?
I read all the comments on this issue, the quick fix you suggested in the app.js did not work for me ... 

For now i had to not use ziggy until it finds a solution ... I am using a work around ... i will share it here .. it might give you an insights  ..

```export default function useUrl() {
    const getUrl = (path: string = '/') => {
        const protocol = window.location.protocol;
        const hostname = window.location.hostname;
        // Ensure leading slash
        const cleanedPath = path.startsWith('/') ? path : `/${path}`;
        return `${protocol}//${hostname}${cleanedPath}`;
    };
    return {
        getUrl,
    };
}
```

```<script setup>
    import useUrl from '@/Composables/useUrl'
    const { getUrl } = useUrl()
</script>
<template>
    <Link :href="getUrl('/admin/grades')">Grades</Link>
</template>
 ```

So i created a function that detect the current protocol and hostname, and i am passing the path to the function....

If you need any explination about this subdomain and muliti tenancy thingy ... feel free to reply. Thanks

**Comment by chrisbjr** [comment]
We stopped using ziggy because it was such a headache to make it work with our muti-tenant routes. We are using spatie's laravel multitenancy package and we've tried various things to make it work with ziggy to no avail. Best way was to stop using it and just point directly to the path itself.
