### ISSUE TITLE
Error when passing array of multiple groups

### ISSUE THREAD

**Issue by DtN1337** [tighten/ziggy#350]
### Expected behavior

From the manual:
> If you want to expose multiple groups you can pass an array of group names

### Current behavior

I get the following error:
```
Argument 1 passed to Tightenco\Ziggy\Ziggy::__construct() must be of the type string or null, array given
```

My code:
```
@routes(['pages', 'guest'])
```

### Versions

- **Laravel**: 8.x
- **Ziggy**: 1.0.0-beta.3

**Comment by bakerkretzmar** [comment]
@DtN1337 yep, I shouldn't have added that typehint. Will fix this asap for beta 5. Thanks!

**Comment by DtN1337** [comment]
Great, thanks! 👍

**Comment by bakerkretzmar** [comment]
@DtN1337 just tagged beta 5, should be fixed. Thanks!
