### ISSUE TITLE
route().current() with root url

### ISSUE THREAD

**Issue by ajnsn** [tighten/ziggy#355]
#### Description

Ziggy v1.0 `route().current()` seems not to work with the root url/route (`/`). 

Console output when navigating to `/`
```
Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at R.current (profile:27)
    at <anonymous>:1:9
```
Refers to Line 82-85 in `src/js/Router.js`

#### Expected behavior

v0.9 worked. 
Works with non-root urls/routes, e.g. `route().current()` on `/profile` returns correctly `profile.edit`

#### Environment

- **Laravel version**: 8.12.0
- **Ziggy version**: 1.0.0

**Related routes**:

```php
Route::name('dashboard.')->group(function () {
    Route::get('/', Dashboard\IndexController::class)->name('index');
});

Route::prefix('profile')->name('profile.')->group(function () {
    Route::get('/', Profile\EditController::class)->name('edit');
    // ...
});
```

**`Ziggy.routes`**:

```js
{
    'dashboard.index': { uri: '/', methods: ['GET', 'HEAD'] },
    'profile.edit': { uri: 'profile', methods: ['GET', 'HEAD'] },
     // ...
}
```

**Ziggy call and context**:

```js
console.log(route().current());
```
Thank you for this great package. Let me know if I missed something!

Alex

**Comment by ajnsn** [comment]
Thank you @bakerkretzmar 💪

**Comment by bakerkretzmar** [comment]
@ajnsn thank you for the heads up! Just tagged `v1.0.1` which fixes this, will be published on npm in a minute too.
