### ISSUE TITLE
Vue 3 compatibility

### ISSUE THREAD

**Issue by hussain4real** [tighten/ziggy#357]
#### Description

I am working with inertia and vue 3 adapter, can't get vue to recognize named routes

**Comment by bakerkretzmar** [comment]
Can you please share what specifically you're trying right now and what isn't working, including the code itself?

**Comment by seklyza** [comment]
In Vue 3 you can just `app.mixin({ methods: { route } })` and then use `route` inside your templates.

**Comment by hussain4real** [comment]
> app.mixin({ methods: { route } })

this is the error i'm getting:
Uncaught TypeError: _inertiajs_inertia_vue3__WEBPACK_IMPORTED_MODULE_1__.app.mixin is not a function.

**app.js**
`import { createApp, h } from "vue";
import { app, plugin } from "@inertiajs/inertia-vue3";
import NProgress from "nprogress";
import { Inertia } from "@inertiajs/inertia";

app.mixin({ methods: { route } });
const el = document.getElementById("app");

Inertia.on("start", () => NProgress.start());

Inertia.on("finish", (event) => {
    if (event.detail.visit.completed) {
        NProgress.done();
    } else if (event.detail.visit.interrupted) {
        NProgress.set(0);
    } else if (event.detail.visit.cancelled) {
        NProgress.done();
        NProgress.remove();
    }
    console.log(event.type);
});

createApp({
    render: () =>
        h(app, {
            initialPage: JSON.parse(el.dataset.page),
            resolveComponent: (name) =>
                import(`@/Pages/${name}`).then((module) => module.default),
        }),
})
    .use(plugin)
    .mount(el);
`

**Comment by hussain4real** [comment]
> Can you please share what specifically you're trying right now and what isn't working, including the code itself?

this is the error i'm getting:
Uncaught TypeError: _inertiajs_inertia_vue3__WEBPACK_IMPORTED_MODULE_1__.app.mixin is not a function.

**app.js**
```javascript
import { createApp, h } from "vue";
import { app, plugin } from "@inertiajs/inertia-vue3";
import NProgress from "nprogress";
import { Inertia } from "@inertiajs/inertia";

app.mixin({ methods: { route } });
const el = document.getElementById("app");

Inertia.on("start", () => NProgress.start());

Inertia.on("finish", (event) => {
    if (event.detail.visit.completed) {
        NProgress.done();
    } else if (event.detail.visit.interrupted) {
        NProgress.set(0);
    } else if (event.detail.visit.cancelled) {
        NProgress.done();
        NProgress.remove();
    }
    console.log(event.type);
});

createApp({
    render: () =>
        h(app, {
            initialPage: JSON.parse(el.dataset.page),
            resolveComponent: (name) =>
                import(`@/Pages/${name}`).then((module) => module.default),
        }),
})
    .use(plugin)
    .mount(el);
```

**app.blade.php**

```HTML
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>
    @routes
    <!-- Scripts -->
    <script src="{{ mix('/js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.css" />
    <link href="{{ mix('/css/app.css') }}" rel="stylesheet" />
    <script src="{{ mix('/js/app.js') }}" defer></script>

</head>

<body>

    @inertia
</body>

</html>
```

**Comment by seklyza** [comment]
```diff
import { createApp, h } from "vue";
import { app, plugin } from "@inertiajs/inertia-vue3";
import NProgress from "nprogress";
import { Inertia } from "@inertiajs/inertia";

- app.mixin({ methods: { route } });
const el = document.getElementById("app");

Inertia.on("start", () => NProgress.start());

Inertia.on("finish", (event) => {
    if (event.detail.visit.completed) {
        NProgress.done();
    } else if (event.detail.visit.interrupted) {
        NProgress.set(0);
    } else if (event.detail.visit.cancelled) {
        NProgress.done();
        NProgress.remove();
    }
    console.log(event.type);
});

createApp({
    render: () =>
        h(app, {
            initialPage: JSON.parse(el.dataset.page),
            resolveComponent: (name) =>
                import(`@/Pages/${name}`).then((module) => module.default),
        }),
})
+    .mixin({ methods: { route } })
    .use(plugin)
    .mount(el);
```

**Comment by hussain4real** [comment]
> ```diff
> import { createApp, h } from "vue";
> import { app, plugin } from "@inertiajs/inertia-vue3";
> import NProgress from "nprogress";
> import { Inertia } from "@inertiajs/inertia";
> 
> - app.mixin({ methods: { route } });
> const el = document.getElementById("app");
> 
> Inertia.on("start", () => NProgress.start());
> 
> Inertia.on("finish", (event) => {
>     if (event.detail.visit.completed) {
>         NProgress.done();
>     } else if (event.detail.visit.interrupted) {
>         NProgress.set(0);
>     } else if (event.detail.visit.cancelled) {
>         NProgress.done();
>         NProgress.remove();
>     }
>     console.log(event.type);
> });
> 
> createApp({
>     render: () =>
>         h(app, {
>             initialPage: JSON.parse(el.dataset.page),
>             resolveComponent: (name) =>
>                 import(`@/Pages/${name}`).then((module) => module.default),
>         }),
> })
> +    .mixin({ methods: { route } })
>     .use(plugin)
>     .mount(el);
> ```

**Wow! problem solve. thanks for the solution**
