### ISSUE TITLE
Error in route().current() when on 404 page

### ISSUE THREAD

**Issue by davejamesmiller** [tighten/ziggy#360]
#### Description

When I'm on the 404 page and I call `route().current('blah')`, I get this exception:

```
TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    Babel 2
    current Router.js:71
    ...
```

I tracked it down to this block:

```js
        const [current, route] = Object.entries(this._config.routes).find(
            ([_, route]) => new Route(name, route, this._config).matchesUrl(url)
        );
```

Because `Object.entries(...).find()` returns `undefined` (no match is found), the destructuring into `[current, route]` throws the error.

Instead I think it needs to be something like:

```js
        const result = Object.entries(this._config.routes).find(
            ([_, route]) => new Route(name, route, this._config).matchesUrl(url)
        );

        if (!result) return false;

        const [current, route] = result;
```

Although I'm not sure if `route().current()` with no parameters should return `false`, `null` or something else.

#### Expected behavior

`route().current('blah')` returns `false`.
`route().current()` returns `false`, `null` or something other than an error.

#### Environment

- **Laravel version**: 8.14.0
- **Ziggy version**: 1.0.1

**Related routes**:

Probably unimportant since it doesn't match any of them.

**`Ziggy.routes`**:

Probably unimportant since it doesn't match any of them.

**Ziggy call and context**:

It's buried in a mixin but basically `route().current('blah')`.

**Comment by bakerkretzmar** [comment]
Yep, this shouldn't error. Will get it fixed. Thanks!
