### ISSUE TITLE
route() in undefined in my react app

### ISSUE THREAD

**Issue by AnasJamous** [tighten/ziggy#365]
#### Description

I am trying to use Laravel named routes in my react app using ziggy, so I followed the docs step by step and i used the @routes directive in my blade view then I am trying to access the route from my component using <InertiaLink href="route('route_name', {parameters}).url()"> and it gives me the same error that says cannot read my_route_name of undefined.
Anyone have an idea how to fix that ?? 

#### Environment

- **Laravel version**: ^8.12
- **Ziggy version**: ^0.9.4

**Comment by bakerkretzmar** [comment]
Can you share more details and the exact code you're using? Is `@routes` _before_ your application javascript?

**Comment by AnasJamous** [comment]
@bakerkretzmar I will share the code in my app.js and the way I am using it
## App.js
`require('./bootstrap');

import { InertiaApp } from '@inertiajs/inertia-react'
import React from 'react'
import { render } from 'react-dom'

const app = document.getElementById('app')

render(
  <InertiaApp
    initialPage={JSON.parse(app.dataset.page)}
    resolveComponent={name => require(`./Pages/${name}`).default}
  />,
  app
)`
## app.blade.view
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <link href="{{ mix('/css/app.css') }}" rel="stylesheet" />
    <script src="{{ mix('/js/app.js') }}" defer></script>
    @routes
  </head>
  <body>
    @inertia
  </body>
</html>`

## In my routes/web.php
`Route::get('/expense/view/{expense}', [ExpenseController::class, 'view'])->name('expense.view');`
## In ExpenseController
` public function view(Expense $expense)
    {
        return Inertia::render('Expenses/view/index', [
            'expense' => $expense,
        ]);
    }`

## package.json
`"dependencies": {
        "@inertiajs/inertia": "^0.4.3",
        "@inertiajs/inertia-react": "^0.3.2",
        "@types/react": "^16.9.56",
        "@types/ziggy-js": "^0.9.0",
        "react": "^17.0.1",
        "react-dom": "^17.0.1",
        "ziggy-js": "^0.9.4"
    }`

Do you need more info ?

**Comment by bakerkretzmar** [comment]
Put `@routes` **before** `<script src="{{ mix('/js/app.js') }}" defer></script>` in your app Blade view and then run `php artisan view:clear`. Does that fix it?

**Comment by AnasJamous** [comment]
@bakerkretzmar It is still giving me the same error:
![image](https://user-images.githubusercontent.com/33751827/99263522-00abe400-2828-11eb-902a-162b0c4f9f47.png)

**Comment by bakerkretzmar** [comment]
@AnasJamous did you install the Composer package, `tightenco/ziggy`, or just the npm one?

**Comment by emielmolenaar** [comment]
I had the same issue in a Vue app, turned out that I had ^0.9.4 installed and the latest ziggy-js package. These two don't work together nicely :)

**Comment by bakerkretzmar** [comment]
Closing because we need more details to be able to debug this further. Feel free to open another issue or comment here if you're still running into this error.
