### ISSUE TITLE
route() is returning a function

### ISSUE THREAD

**Issue by stevethomas** [tighten/ziggy#366]
#### Description
Since upgrading to v1, I am getting a really weird result on one of my routes. From my Vue component, it is returning my route parameter as a function definition, eg:

`http://codinglabs.test:3000/hq/shifts/function%20shift()%20%7B%20%5Bnative%20code%5D%20%7D?id=6&employee_id=3&cycle_id=1&project_id=2&date=2020-11-04&created_at=2020-11-16T03%3A59%3A38.000000Z&updated_at=2020-11-16T03%3A59%3A38.000000Z&project=2`

`shift()` is a computed property on this component, but it returns an object or undefined.

Below are some various results I got from the console:

![image](https://user-images.githubusercontent.com/1127412/99214560-2df29500-281c-11eb-8c1b-eb80f2f8e49e.png)

#### Expected behavior
Like the working `route('hq.projects.show')` above, I expect ziggy to determine the correct route with the object from the ID.

#### Environment

- **Laravel version**:  8.14
- **Ziggy version**:  1.0.2

**Related routes**:

```php
Route::middleware('auth')->prefix('hq')->name('hq.')->group(function () {
  // these are all fine
  Route::resource('projects', Controllers\Hq\ProjectController::class);   

  // only the store method is working with route()
  Route::resource('shifts', Controllers\Hq\ShiftController::class)->only(['store', 'update', 'destroy']);
});
```

**`Ziggy.routes`**:

```
hq.shifts.update:
bindings: {shift: "id"}
methods: (2) ["PUT", "PATCH"]
uri: "hq/shifts/{shift}"
__proto__: Object
```

**Ziggy call and context**:

```js
// Shift.vue methods
      update(project) {
        this.$inertia.put(route('hq.shifts.update', this.shift), {
          project_id: project.id,
        }, {
          preserveScroll: true
        })
      },
```

**Theory**
I figured it had to be some kind of naming conflict, so I:
- commented out my `shift()` method ❌
- renamed `shift` to `shifty` in the component ❌
- renamed the route parameter `{{shift}}` to `{{shifty}}` in the routes ✅

So I guess `shift` is getting evaluating in JavaScript somehow? I'd like to do a PR but unfortunately it is a bit beyond my js abilities.

**Comment by bakerkretzmar** [comment]
Whoa, very weird. I'll take a look this week, thanks for the detailed explanation.

**Comment by bakerkretzmar** [comment]
Yeah this is happening because all javascript objects have a `shift` property and I'm checking for property existence with a shorthand instead of with `hasOwnProperty`.... will fix this today, thanks for your patience!
