### ISSUE TITLE
CORS policy issues

### ISSUE THREAD

**Issue by ljsharp** [tighten/ziggy#368]
Access to XMLHttpRequest at 'http://localhost/leads' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource

What can I fix this issue please?

**Comment by bakerkretzmar** [comment]
I would recommend the MDN page for CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS. You may need to adjust your `APP_URL` value or your local setup.

Closing because this is not an issue with Ziggy.
