### ISSUE TITLE
"tightenco/ziggy": "^0.9.4" cannot upgrade to 1.0.2

### ISSUE THREAD

**Issue by tingan** [tighten/ziggy#372]
Hi,
I am using ziggy 0.9.4 . composer cannot upgrade to 1.0.2. if I manually change composer.json to ^1.0, will it break anything? also does the 1.0.2 require php 7.4 (the arrow function)? as i am using php 7.3. Thanks.

**Comment by bakerkretzmar** [comment]
Yes, v1 contains breaking changes, which you can find in the [Upgrade Guide](https://github.com/tighten/ziggy/blob/main/UPGRADING.md#upgrading-from-09x-to-1x). Ziggy's dependencies are listed in [`composer.json`](https://github.com/tighten/ziggy/blob/main/composer.json), PHP 7.3 will work fine.
