### ISSUE TITLE
route generated not https

### ISSUE THREAD

**Issue by vortechron** [tighten/ziggy#373]
what I've done:

- forceSchema on provider
- env set APP_URL
- clear all cache

It's very weird and frustrating, when I debug at console, I saw "template" not holding https domain.

**Comment by vortechron** [comment]
i dunno how its somehow fixed :(

**Comment by tiaxter** [comment]
The solution is set the APP_URL to an https url

**Comment by vortechron** [comment]
@tiaxter the solution is actually after you do all of these:

-forceSchema on provider
-env set APP_URL
-clear all cache

finally, you need to logout n login back

**Comment by tiaxter** [comment]
> @tiaxter the solution is actually after you do all of these:
> 
> -forceSchema on provider
> -env set APP_URL
> -clear all cache
> 
> finally, you need to logout n login back

I only set APP URL to an HTTPS url and clear cache
And i solved
