### ISSUE TITLE
Generated routes do not retain the port number

### ISSUE THREAD

**Issue by fsavalam** [tighten/ziggy#374]
**Description**

I'm using Ziggy with on a Laravel/Vue project. I installed and configured ziggy as per the documentation, .i.e

```js
@routes
<script src="{{ mix('/js/app.js') }}" defer></script>
```

My app.js looks like:

```js
import { createApp, h } from 'vue'
 
const app = createApp({
  // ...
})

app.mixin({
  methods: { route: window.route }
})

```

Every looks good, except my routes are missing the port number.
instead of: **localhost:8000/home**, 
I have: **localhost/home**

How can I configure it to add the port number (when I'm using on my local machine)?
Thanks

**Environment**
- **Laravel**: ^8.12
- **Ziggy**: ^1.0
- **Vuejs**: 3
- **Windows 10 Pro**

**Comment by bakerkretzmar** [comment]
@fsavalam for now as a quick fix, this should work if you add `:8000` to your `APP_URL` environment variable.

It seems like #334 may have broken automatic support for ports... I'll look into that.

**Comment by fsavalam** [comment]
Thanks
