### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by pmochine** [tighten/ziggy#375]
#### Description

Ziggy fails when you add parameters when they don't exist.

Before version 1, I could just let the code be like this:

```
  axios.post(route(endpoint, this.food.id), data)
                    .then(this.saved)
                    .catch(this.failed);
```

The endpoint is dynamically set. However, if you have URLs that don't have parameters it now fails.

```
VM12 letscook:115 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at VM12 letscook:115
    at Array.reduce (<anonymous>)
    at R.s (VM12 letscook:115)
    at new R (VM12 letscook:115)
    at VM12 letscook:115
    at _callee$ (offerFood.js:21)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (CountryList.vue:45)
```

#### Expected behavior

It should work, even if the parameter is useless in some cases.

#### Current solution

// not that nice :D

                let url = '';

                if (endpoint === 'uploadImage') {
                    url = route(endpoint);
                } else {
                    url = route(endpoint, this.food.id);
                }

                axios.post(url, data)
                    .then(this.saved)
                    .catch(this.failed);

#### Environment

- **Laravel version**:   v8.14.0
- **Ziggy version**:  v1.0.1

**Related routes**:

```php
Route::post('/upload/image', 'Api\ImageUploadController@store')->name('uploadImage');
```

**`Ziggy.routes`**:

```js
      "uploadImage": {
            "uri": "api\/upload\/image",
            "methods": ["POST"]
        },
```

**Comment by bakerkretzmar** [comment]
What is `this.food` when you aren't using it? `undefined`?

**Comment by pmochine** [comment]
@bakerkretzmar thanks for the fast reply. `this.food` is a vue prop und is always set with a value. So there is no `undefined`. 

To make it short. It fails even if I write: `route('uploadImage', 'some-random-value')`

**Comment by bakerkretzmar** [comment]
@pmochine okay got it, thanks. I think I understand what's happening, but I'm not sure that ignoring the extra param is actually the correct behaviour here. In an object, extra parameters are appended to the query string:

```js
route(endpoint, { id: this.food.id });
// If the route has no params, this will return "http://endpoint.test/path?id=1"
```

Laravel's `route()` helper also works this way, except it can handle strings and arrays too:

```php
Route::get('no-params', function () {})->name('no-params');
Route::get('one-param/{param}', function () {})->name('one-param');

app('router')->getRoutes()->refreshNameLookups();

route('no-params');                 // "http://localhost/no-params"
route('no-params', 'foo');          // "http://localhost/no-params?foo"
route('one-param', 'foo');          // "http://localhost/one-param/foo"
route('one-param', ['foo', 'bar']); // "http://localhost/one-param/foo?bar"
```

I agree that Ziggy should not error here, but rather than ignoring the params, I would actually expect it to append them to the query like this. What do you think? I know this doesn't solve your problem, sorry! 🙃

**Comment by pmochine** [comment]
@bakerkretzmar Yeah I'm fine with appending this to the URL, at least it's not failing then 🙂

**Comment by bakerkretzmar** [comment]
Now that I suggested that I realize it's not possible, since we've configured `qs` to filter out null query parameters... silently ignoring them might be the way to go after all! Still working on this, thanks for your patience.
