### ISSUE TITLE
How to check isActive with query param?

### ISSUE THREAD

**Issue by deantheiceman** [tighten/ziggy#380]
I am using 

```
link = 'orders'
params = {status: 'pending'}

const isActive = route().current(link, params)
```

But isActive seems to always return true even if my url is /orders?status=false
I've tried the main branch and also get the same problem, how can I filter isActive to be inclusive of query param?

**Comment by bakerkretzmar** [comment]
Thanks! You're doing everything correctly, this is a bug and should be fixed in the next week. See #379.
