### ISSUE TITLE
Vue setup:  Can't resolve 'ziggy' in '[project path]\resources\js\pages'

### ISSUE THREAD

**Issue by Chinyoka1** [tighten/ziggy#381]
#### Description

I've tried to set up ziggy in my Laravel/Vue MPA project, following the instructions for javascript frameworks and vue. I ran `php artisan ziggy:generate` and set it up in my javascript file like show in the instructions, with a Vue mixin. The issue is the following line: 
`import route from 'ziggy';`
When I build with yarn watch, I get this error:
`ERROR in ./resources/js/pages/welcome.js
Module not found: Error: Can't resolve 'ziggy' in '[my project path]\resources\js\pages'
 @ ./resources/js/pages/welcome.js 6:0-27 12:13-19
 @ multi ./resources/js/pages/welcome.js ./resources/css/app.css`

I'm probably missing something, do I have to install a seperate npm package, or where do I get this module from? I found nothing in the documentation.

#### Expected behavior

Not getting an error, probably.

#### Environment

- **Laravel version**: 8.16.1
- **Ziggy version**:  1.0.3

**Comment by bakerkretzmar** [comment]
If your Vue app is being mounted on a page that is also a Blade view, you can use the `@routes` directive and then you don't need to `import route from 'ziggy'` at all. Otherwise, you can either alias `ziggy` to `vendor/tightenco/ziggy/dist` or install the npm package, depending on your project setup. The docs section on this is [here](https://github.com/tighten/ziggy#javascript-frameworks).

Let me know if that does it!

**Comment by Chinyoka1** [comment]
I tried using the @routes directive, but when try to direct to a route, nothing happens. I also tried setting the alias in my webpack.mix.js, but that gives me the webpack error "alias is not a function". It's not an SPA or a seperate project, it's all in the Laravel project, so I assume I don't need the npm package, right?

**Comment by bakerkretzmar** [comment]
That's right, you shouldn't need the npm package. Make sure you're using the right alias method, `mix.alias` is new in Mix 6 which is not officially released yet. 

Can you share the Laravel routes that are affected, the dev console output of `Ziggy.routes`, and the actual code calling the `route()` helper? Thanks.

**Comment by Chinyoka1** [comment]
What would be the correct alias method then?

These are my routes:
`Route::get('/', [WelcomeController::class, 'index'])->name('welcome');
Route::get('/login', [LoginController::class, 'index'])->name('login.index');`

I'm in "welcome" and trying to direct to "login.index" from a vue component.

Like I said, I can't even load my website because I get the error on build.

Here's my route function:

`methods: {
        goToLogin() {
            route('login.index');
        },
}`

**Comment by bakerkretzmar** [comment]
Take a look at [the section of the Readme on setting up Ziggy with Javascript frameworks](https://github.com/tighten/ziggy#javascript-frameworks). With Mix 5 it would look like this:

```js
mix.webpackConfig({
    resolve: {
        alias: {
            ziggy: path.resolve('vendor/tightenco/ziggy/dist'),
        },
    },
});
```

Like Laravel's helper, Ziggy's `route()` function returns a string, it doesn't perform any navigation for you. Your `goToLogin()` method will return something like `http://my-app.test/login`.

**Comment by Chinyoka1** [comment]
Ohhh, I see. I learned about ziggy in a thread on Laracasts, and I thought that it does exactly that. Thank you for clarifying.
