### ISSUE TITLE
Source maps specified in index.js but not included in blade

### ISSUE THREAD

**Issue by johanobergman** [tighten/ziggy#382]
#### Description

The dist js files specify a `sourceMappingUrl`, but since no source maps are included in blade it results in a developer console error, 404 for `index.js.map`.

#### Proposed solution

Either completely skip source map in the build, or include them as part of the `@routes` directive (but then - should they be included in production or not?). Perhaps users could import the js using their build tool (leaving source map generation up to them), while using blade only for the JSON routes.

**Comment by bakerkretzmar** [comment]
I like the idea of inlining them in non-production environments, they're bigger than Ziggy itself but still relatively tiny overall. Microbundle doesn't seem to support this but Rollup does and it looks straightforward, so I might PR it.

As for using `@routes` just for the JSON, if I'm understanding you correctly, this should already be possible with the `ziggy.skip-route-function` config option.

**Comment by jandreasn** [comment]
@bakerkretzmar This seems more like a bug than an enhancement to me. We are using `@routes` and the route helper and since updating Ziggy we are getting warnings in the developer console on all pages where Ziggy is used, in production. Please consider relabeling this issue so it might get a higher priority. 

>DevTools failed to load SourceMap: Could not load content for https://www.example.com/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by bakerkretzmar** [comment]
My PR to add support for inline sourcemaps was just merged into microbundle, so as soon as they tag a release this should be trivial to add. Thanks for your patience.

Note to future me: in production just strip out the sourcemap line entirely to avoid error messages.

**Comment by graceoflives** [comment]
Hi. I am using Safari and adding @routes to blade make pages unable to load anything because Safari returns a 404 error on sourcemaps "index.js.map".
I have fixed it temporarily by creating a dummy index.js.map file.
Please consider release the merged fix. Thank you for the awesome lib.

**Comment by bakerkretzmar** [comment]
@graceoflives just released v1.0.5 👍🏻
