### ISSUE TITLE
How to check the current route using an absolute URL

### ISSUE THREAD

**Issue by Propaganistas** [tighten/ziggy#384]
Thank you for release `1*`. This release marks several important and highly anticipated features!

There's one thing that's not very clear how to obtain the desired result.

`route().current()` accepts a route name and parameters to check if the arguments make up for the current URL.
How can I achieve the same check, but with an absolute URL instead?

```
route().current('http://example.net/some/path')
```

I might have missed something, but it seems Ziggy's API doesn't provide a straightforward way to achieve this, even though all of the building blocks are in place (use current route's `Route` object and run `matchesUrl()`)?

**Comment by bakerkretzmar** [comment]
What would be the difference between `route().current('http://example.net/some/path')` and `window.location.href === 'http://example.net/some/path'`?

**Comment by Propaganistas** [comment]
Valid point of which I didn't even think about previously. Overengineering is often lurking around the corner I guess...

However, when thinking about this, `window.location.href` includes the query string if present and will therefore most probably invalidate the equality check in such cases. But of course the query string can be stripped before comparison. I guess this will be a matter of what should or can be expected regarding the `current()` method.

**Comment by bakerkretzmar** [comment]
Yep, exactly. Not a bad idea, but the `current()` method is very focused on route names so this feels a bit out of scope, at least right now.

As for the query string, yeah you'd have to strip that yourself. You could use `window.location.origin + window.location.pathname` or `window.location.href.slice(0, window.location.href.indexOf('?'))` or something.
