### ISSUE TITLE
ReflectionException "Class self does not exist"

### ISSUE THREAD

**Issue by xavi7th** [tighten/ziggy#391]
#### Description

Great piece of software. I have been using it seamlessly for a while and have enjoyed working with ziggy.

I just upgraded to the latest version and I noticed an issue when I use DI with self. 

Given a route like this
```
Route::get('/debit-card/{debitCard}/authorize', [self::class, 'authorizeDebitCard'])->name('appuser.cards.authorize');
```
And a controller method like this
```
  public function authorizeDebitCard(Request $request, self $debitCard)
  {
    return PaystackTransaction::initializeTransaction($request, 50, 'Debit card authorization', route('appuser.debit_card.verify', $debitCard->uuid));
  }

```

Notice that I inject the DebitCard into the method using self. 

This throws an error from ReflectionMethod.

#### Expected behavior

After some digging around I found that the problem was coming from "vendor/tightenco/ziggy/src/Ziggy.php: 157"

Using the getClass method of the reflectionParameter class fixes the resolution of self to the actual class itself. 

That is when I change 
```
$model = $parameter->getType()->getName();
```
to 
```
$model = $parameter->getClass()->getName();
```
This fixes it.

#### Environment

 "require": {
        "php": "^7.2.5",
        "inertiajs/inertia-laravel": "^0.3.5",
        "intervention/image": "^2.5",
        "laravel-validation-rules/credit-card": "^1.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.4.1",
        "nwidart/laravel-modules": "^7.1",
        "orangehill/iseed": "^2.6",
        "tightenco/ziggy": "^1.0",
        "tymon/jwt-auth": "^1.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.3",
        "barryvdh/laravel-ide-helper": "^2.6",
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^5.1",
        "phpunit/phpunit": "^8.5",
        "rachidlaasri/travel": "^1.0"
    },

Once again great software.

**Comment by bakerkretzmar** [comment]
I don't think that controller method is valid, `self` in that context would be the controller itself, but you probably want it to be the `DebitCard` model.

Where are you declaring the route?

**Comment by xavi7th** [comment]
> I don't think that controller method is valid, `self` in that context would be the controller itself, but you probably want it to be the `DebitCard` model.
> 
> Where are you declaring the route?

_I knew I should have commented on that._

I have a lot of routes in my application, so to make them manageable, I abstracted the controller methods/routes away into the respective model. So in this case all the routes that pertain to the 'DebitCards' are in the 'DebitCard' model.
