### ISSUE TITLE
Get Route Collection Via A Simple function

### ISSUE THREAD

**Issue by devbapidey** [tighten/ziggy#401]
Sometimes we need to create a dynamic menu or such kind of UI. If there is a function to get route list for specific name / group save lot's of time. I am using currently using inertiajs and I really feel that feature is missing.https://stackoverflow.com/a/29943111/9279246 here is a code that's I currently useing.

**Comment by bakerkretzmar** [comment]
You can use route names to do something quite similar:

```php
Route::name('users.')->group(function () {
    Route::get('users', /* ... */)->name('index');
    Route::get('users/{user}', /* ... */)->name('show');
    Route::post('users', /* ... */)->name('store');
});

Route::name('teams.')->group(function () {
    Route::get('teams', /* ... */)->name('index');
    Route::get('teams/{team}', /* ... */)->name('show');
    Route::post('teams', /* ... */)->name('store');
});

// This will give you all the routes that start with `users.`
collect(app('router')->getRoutes()->getRoutesByName())->filter(fn ($route, $name) => Str::is('users.*', $name));
```

Closing for now since this isn't an issue with Ziggy.
