### ISSUE TITLE
[Vue warn]: Error in v-on handler: "Error: Ziggy Error: route 'employees.update' is not found in the route list"

### ISSUE THREAD

**Issue by isaacdarcilla** [tighten/ziggy#402]
#### Description

[Vue warn]: Error in v-on handler: "Error: Ziggy Error: route 'employees.update' is not found in the route list"

```
found in

---> <EmployeeEditModal> at resources/js/Shared/Modals/EmployeeEditModal.vue
       <PersonalInformation> at resources/js/Shared/PersonalInformation.vue
         <Edit> at resources/js/Pages/Contacts/Edit.vue
           <Layout> at resources/js/Shared/Layout.vue
             <Inertia>
               <Root>
```

EmployeeEditModal.vue save() method

```js
          save() {
             this.$inertia.put(
                this.route("employees.update", this.employee.id), this.form, {
                    onStart: () => (this.sending = true),
                    onFinish: () => (this.sending = false)
                }
            );
         },
```

Laravel route

```php
Route::put('employees/{contact}', [ContactsController::class, 'update'])
    ->name('employees.update')
    ->middleware('auth');
```

#### Environment

- **Laravel version**: 8
- **Ziggy version**:

**Comment by bakerkretzmar** [comment]
What version of Ziggy are you using, and what do you see for that route in `php artisan route:list` and `console.log(Ziggy.routes)`?

**Comment by isaacdarcilla** [comment]
**Resolve**: I have to change the request method to **POST**. Thanks!

**Comment by rahulsharma0657** [comment]
Try to give name in the route 
`Route::get('good/list','GoodController@list')->name("good.list");`

The above solved my issue

**Comment by matthelosh** [comment]
How to handle that error to give human friendly page?
