### ISSUE TITLE
Relocate Ziggy Constant in front end so it is not shown in view page source.

### ISSUE THREAD

**Issue by Mekiamohammed** [tighten/ziggy#403]
I am using Ziggy to expose my Laravel routes for vue using inertia js .
but while i view the page source i can clearly see all of laravel routes like.
````
    const Ziggy = {"url":"http:\/\/127.0.0.1:8787","port":8787,"defaults":{},"routes": 
    ......

"sup_finish_tt_order":{"uri":"front\/finishorder","methods":["POST"]},"assign__tt":{"uri":"front\/assigntt","methods":["POST"]},"technicians":{"uri":"technicians","methods":["GET","HEAD"]},"change-password":{"uri":"change-password","methods":["GET","HEAD"]},"reset.password":{"uri":"c
----------
````

is there  anyway to movw this to other file e.g app.js

**Comment by bakerkretzmar** [comment]
Yes, take a look at the [JavaScript frameworks](https://github.com/tighten/ziggy#javascript-frameworks) and [Filtering Routes](https://github.com/tighten/ziggy#filtering-routes) sections of the Readme. Feel free to comment here again if you have specific questions or run into issues setting it up!

**Comment by seyid20** [comment]
If  possible it would be great to create a repo  that demonstrates advance configuration with  frontend frameworks .
Laravel vue  and inertia js stack is promoting Ziggy , there will more and more confused users  [like me], please support.
