### ISSUE TITLE
Error in Query Params

### ISSUE THREAD

**Issue by filippodicostanzo** [tighten/ziggy#404]
#### Description

Unexpected error in query string

#### Expected behavior

This is my route in Vue Component

` <a class="btn btn-default btn-xs" :href="route('posts.show', [{id: item.id}, {event: 1}, {venue: 2}, {page: 5}])">`

And this is the Result:
`posts/32?0[event]=1&1[venue]=2&2[page]=5`

There are wrong characters like an array of params [0] event [1]venue

#### Environment

- **Laravel version**: 8.0
- **Ziggy version**: 0.9.4

**Comment by bakerkretzmar** [comment]
Can you please share your route definition for that route and the relevant portion of the output when you run `console.log(Ziggy.routes)`?

**Comment by filippodicostanzo** [comment]
This is the route generated with ziggyjs:
`"posts.show":{"uri":"admin\/posts\/{post}","methods":["GET","HEAD"],"domain":null}`

and this is the console log of that path:

```
posts.show:
domain: null
methods: Array(2)
0: "GET"
1: "HEAD"
length: 2
__proto__: Array(0)
uri: "admin/posts/{post}"
```

can I share anything else that may be useful?

**Comment by filippodicostanzo** [comment]
I think the problem is when i call a route with id.

I try to change route with optional parameters but doesn't work

` Route::get('/posts/{id?}', [UserController::class, 'show'])->name('posts.show');
`

**Comment by bakerkretzmar** [comment]
Try passing all the params as just one object:

```js
route('posts.show', { id: item.id, event: 1, venue: 2, page: 5 });
```

There was an issue with Ziggy v0.9.x at some point that had to do with passing params called `id`, so if the above doesn't work, I would suggest either updating to Ziggy v1 or separating out the query parameters like this:

```js
route('posts.show', item.id).withQuery({ event: 1, venue: 2, page: 5 });
```

**Comment by filippodicostanzo** [comment]
Resolved with 

`route('posts.show', item.id).withQuery({ event: 1, venue: 2, page: 5 });`

Thank You!
