### ISSUE TITLE
Set up Ziggy with Vue Js & Inertia

### ISSUE THREAD

**Issue by seyid20** [tighten/ziggy#406]
Ziggy works as expected when we use @route directive.
but i dont want to use the directive instead we try   configuring it  with vue js . but it seems i am having a difficulty mounting it.
here is the detail and we are ready to give additional detail.

//copied from SO
I am using Ziggy for my Laravel, Vue.js and Inertia js project. In the view page source, I can clearly see all of the Laravel routes.

```
<script type="text/javascript">
    const Ziggy = {"url":"http:\/\/127.0.0.1:8787","port":8787,"defaults":{},"routes": 
    ......

"sup_finish_tt_order":{"uri":"front\/finishorder","methods":["POST"]},"assign__tt":{"uri":"front\/assigntt","methods":["POST"]},"technicians":{"uri":"technicians","methods":["GET","HEAD"]},"change-password":{"uri":"change-password","methods":["GET","HEAD"]},"reset.password":{"uri":"c
----------
</script>
```

Is there any way to relocate this Ziggy object in app.js or make it less obvious? Based on the [Ziggy](https://github.com/tighten/ziggy) documentation and the answer attempted here I try importing it in app.js,a but it's not working.

> Uncaught TypeError: Cannot read property 'prototype' of undefined
>     at Object.inherits (app.js:124712)
>     at Object.<anonymous> (app.js:68991)
>     at Object../node_modules/irc/lib/irc.js (app.js:69342)
>     at __webpack_require__ (app.js:64)
>     at Object../node_modules/ziggy/index.js (app.js:140181)
>     at __webpack_require__ (app.js:64)
>     at Module../resources/js/app.js (app.js:141504)
>     at __webpack_require__ (app.js:64)
>     at Object.0 (app.js:142081)
>     at __webpack_require__ (app.js:64)

**___________________________Set up ______________________________________**

//Backend
```
$ php artisan ziggy:generate
File generated!
```
//  sample /resources/js/ziggy.js file
```
const Ziggy = {"url":"http:\/\/127.0.0.1:8787","port":8787,"defaults":{},"routes":{"debugbar.openhandler":{"uri":"_debugbar\/open"  /*..... All named routes as expeted */


if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    for (let name in window.Ziggy.routes) {
        Ziggy.routes[name] = window.Ziggy.routes[name];
    }
}

export { Ziggy };


```
// /resources/js/app.js
```
require('./bootstrap')
import Vue from 'vue'
import VueMeta from 'vue-meta'
import PortalVue from 'portal-vue'
import { App, plugin } from '@inertiajs/inertia-vue'
import { InertiaProgress } from '@inertiajs/progress/src'

// Ziggy start here
import route from 'ziggy';
import { Ziggy } from './ziggy';

Vue.mixin({
    methods: {
        route: (name, params, absolute, config = Ziggy) => route(name, params, absolute, config),
    },
});
// ziggy end here



import { BootstrapVue, IconsPlugin } from 'bootstrap-vue'
Vue.use(BootstrapVue)
Vue.use(IconsPlugin)
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'
import { mixins } from 'vue-chartjs'
import TreeBrowser from './Pages/globalComponents/TreeBrowser.vue'
//Vue.config.productionTip = false
Vue.mixin({ methods: { route: window.route } })
Vue.use(plugin)
Vue.use(PortalVue)
Vue.use(VueMeta)
Vue.component('TreeBrowser', TreeBrowser)
InertiaProgress.init()

let app = document.getElementById('app')

new Vue({
    metaInfo: {
        titleTemplate: (title) => title ? `${title} - FNV` : 'FNV yours'
    },
    render: h => h(App, {
        props: {
            initialPage: JSON.parse(app.dataset.page),
            resolveComponent: name =>
                import (`./Pages/${name}`).then(module => module.default),
        },
    }),
}).$mount(app)
```
// /webpack.mix.js

```
const mix = require('laravel-mix');
const path = require('path');
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css');

mix.webpackConfig({
    resolve: {
        alias: {
            ziggy: path.resolve('vendor/tightenco/ziggy/dist'),
        },
    },
});
```
usage of ziggy ex in Login.vue
```
this.$inertia.post(this.route('login.attempt'), data, {
        onStart: () => this.sending = true,
        onFinish: () => this.sending = false,
      })
    ```

**Comment by bakerkretzmar** [comment]
Is that error happening during the build (and does the build fail?) or in the browser console?

What version of Mix and Ziggy are you using?

Your setup looks correct to me, this feels like it might not be an issue with Ziggy.

**Comment by seyid20** [comment]
1. No error happed during building and the build finished successfully
2.  the  error in console is 
```
Uncaught TypeError: Cannot read property 'prototype' of undefined
at Object.inherits (app.js:124712)
at Object. (app.js:68991)
at Object../node_modules/irc/lib/irc.js (app.js:69342)
at webpack_require (app.js:64)
at Object../node_modules/ziggy/index.js (app.js:140181)
at webpack_require (app.js:64)
at Module../resources/js/app.js (app.js:141504)
at webpack_require (app.js:64)
at Object.0 (app.js:142081)
at webpack_require (app.js:64)
```
3 .What version of mix you are using Laravel-mix 5.0.4   and  Ziggy 1.0.5
4. When using @routes directive it does work as expected.
5. removing all other libraries but  ziggy does not help (the app not mounted)
but f i were to remove the line ``` import route from 'ziggy'; ``` the app mounted again

**Comment by bakerkretzmar** [comment]
Can you dig into the stack trace a bit more or share the snippets that each of those lines is coming from?

For example, what is the actual code at `Object../node_modules/ziggy/index.js (app.js:140181)` and `Module../resources/js/app.js (app.js:141504)`?

Is this code in a public repo? If not, can you create a repo that reproduces this issue and share it with us? The setup you've shared so far is correct and that error looks like it might not be coming from Ziggy.

**Comment by seyid20** [comment]
based on the accepted answers and by removing ``` Vue.mixin({ methods: { route: window.route } }) ``` it works
