### ISSUE TITLE
Group route name prefix doesn't work

### ISSUE THREAD

**Issue by vahidrk** [tighten/ziggy#408]
#### Description
Hi
I'm using Laravel Inertia which comes with ziggy installed by default.
If I define a group route name prefix like this it works fine:

`Route::name('admin.')->group(function () {
  // my admin routes
{);`

But when defined like below, it doesn't generate the routes:

`Route::group([
    'prefix'     => 'admin',
], function () {
  // my admin routes
});`

#### Expected behavior
This one is my route group for admin area. Running "PHP artisan ziggy:generate" does not generate the routes within the group. (e.g: admin.posts.show, etc)

`Route::group([
    'prefix'     => 'admin',
    'middleware' => ['auth:sanctum', 'verified'],
    'prefix'     => 'admin',
], function () {
  // my admin routes
});`

#### Environment

- **Laravel version**: 8.12
- **Ziggy version**: 1.0.5

**Related routes**:

```php
Route::get('/', 'HomeController')->name('home');
```

**`Ziggy.routes`**:

```js
{
    home: {
        uri: '/',
        methods: ['GET', 'HEAD'],
    },
    // ...
}
```

**Ziggy call and context**:

```js
// ApiClient is a wrapper around axios
ApiClient.get(route('home', { lang: 'en' }));
```

**Comment by bakerkretzmar** [comment]
Can you please share your route definitions and `Ziggy.routes`?

The `name` method in `Route::name('admin.')->group(...)` is an alias for the `as` attribute, so its actually equivalent to `Route::group(['as' => 'admin.'], ...)`.

`prefix` (which prefixes the route's URI, not its name) should work either way, and does for me locally in a new Laravel app.

See laravel/framework#32528 and laravel/framework#34845.

**Comment by bakerkretzmar** [comment]
Closing this because I think it's an issue with your route definitions, but please comment again if you're still having this issue!
