### ISSUE TITLE
uri without https

### ISSUE THREAD

**Issue by andyyou** [tighten/ziggy#410]
#### Description

I use `@routes` of ziggy with Laravel and deploy it to Heroku as host. The problem is `@routes` render in HTML the protocol of `uri` is `http`. I want it to be https or change depend on current URL, but even I set up `APP_URL` it doesn't change.

I am not sure it only happen on Heroku or not. Thanks

#### Expected behavior

`route()` helper get correct uri. For example: `https://demo.herokuapp.com` shouldn't get `http://demo.herokuapp.com` which will get `Error: Network Error`.

#### Environment

- **Laravel version**: 8.29
- **Ziggy version**: 1.0.5

**Related routes**:

All

**`Ziggy.routes`**:

```js
{
    "login": {
        "uri": "login",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "logout": {
        "uri": "logout",
        "methods": [
            "POST"
        ]
    },
    "password.request": {
        "uri": "forgot-password",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "password.reset": {
        "uri": "reset-password/{token}",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "password.email": {
        "uri": "forgot-password",
        "methods": [
            "POST"
        ]
    },
    "password.update": {
        "uri": "reset-password",
        "methods": [
            "POST"
        ]
    },
    "register": {
        "uri": "register",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "verification.notice": {
        "uri": "email/verify",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "verification.verify": {
        "uri": "email/verify/{id}/{hash}",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "verification.send": {
        "uri": "email/verification-notification",
        "methods": [
            "POST"
        ]
    },
    "user-profile-information.update": {
        "uri": "user/profile-information",
        "methods": [
            "PUT"
        ]
    },
    "user-password.update": {
        "uri": "user/password",
        "methods": [
            "PUT"
        ]
    },
    "password.confirm": {
        "uri": "user/confirm-password",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "password.confirmation": {
        "uri": "user/confirmed-password-status",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "two-factor.login": {
        "uri": "two-factor-challenge",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "landing": {
        "uri": "/",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "oauth.login": {
        "uri": "login/{provider}",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "oauth.callback": {
        "uri": "login/{provider}/callback",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "projects.index": {
        "uri": "projects",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "projects.create": {
        "uri": "projects/create",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "profile.show": {
        "uri": "user/profile/{component?}",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "other-browser-sessions.destroy": {
        "uri": "user/other-browser-sessions",
        "methods": [
            "DELETE"
        ]
    },
    "current-user.destroy": {
        "uri": "user",
        "methods": [
            "DELETE"
        ]
    },
    "teams.index": {
        "uri": "teams",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "teams.create": {
        "uri": "teams/create",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "teams.store": {
        "uri": "teams",
        "methods": [
            "POST"
        ]
    },
    "teams.show": {
        "uri": "teams/{team}",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "teams.edit": {
        "uri": "teams/{team}/edit",
        "methods": [
            "GET",
            "HEAD"
        ]
    },
    "teams.update": {
        "uri": "teams/{team}",
        "methods": [
            "PUT"
        ]
    },
    "teams.destroy": {
        "uri": "teams/{team}",
        "methods": [
            "DELETE"
        ]
    },
    "current-team.update": {
        "uri": "current-team",
        "methods": [
            "PUT"
        ]
    },
    "team-members.store": {
        "uri": "teams/{team}/members",
        "methods": [
            "POST"
        ]
    },
    "team-members.update": {
        "uri": "teams/{team}/members/{user}",
        "methods": [
            "PUT"
        ]
    },
    "team-members.destroy": {
        "uri": "teams/{team}/members/{user}",
        "methods": [
            "DELETE"
        ]
    },
    "team-invitations.accept": {
        "uri": "team-invitations/{invitation}",
        "methods": [
            "GET",
            "HEAD"
        ],
        "bindings": {
            "invitation": "id"
        }
    },
    "team-invitations.destroy": {
        "uri": "team-invitations/{invitation}",
        "methods": [
            "DELETE"
        ],
        "bindings": {
            "invitation": "id"
        }
    },
    "user-pinned-teams.store": {
        "uri": "user-pinned-teams/{team}",
        "methods": [
            "POST"
        ],
        "bindings": {
            "team": "id"
        }
    },
    "user-pinned-teams.destroy": {
        "uri": "user-pinned-teams/{team}",
        "methods": [
            "DELETE"
        ],
        "bindings": {
            "team": "id"
        }
    }
}
```

**Comment by bakerkretzmar** [comment]
Pretty sure this is the same issue as #313, which was fixed but later reverted. Will get another fix out soon.

I'm surprised it's affecting Heroku, they may be doing TLS termination but I would have thought it would be more transparent and the app wouldn't have to know about and would just see HTTPS everywhere.

Can you clear your view and route caches? What are the values of the other top-level keys in the `Ziggy` object (everything else besides `Ziggy.routes`)?

**Comment by andyyou** [comment]
@bakerkretzmar Thanks so much for answer.

**Comment by andyyou** [comment]
![Screen Shot 2021-03-12 at 4 22 23 PM](https://user-images.githubusercontent.com/665690/110913371-0639b680-8350-11eb-8ac7-043b5ad0d538.png)

After clear cache I get the same result. I have set up a `APP_URL` but it doesn't work. Should I publish the JS or is there any way I can set by backend side

**Comment by suhaboncukcu** [comment]
I have the same problem with cloudflare https redirect

**Comment by jespejoh** [comment]
Same issue on Heroku, but solved with a workaround, according to this suggestion (https://github.com/tighten/ziggy/pull/313#issuecomment-670569994): 

`

        @routes
        <script>
            Ziggy.url = '{{ env('APP_URL') }}'
        </script>
`

Not ideal, but it works for now :)

**Comment by andyyou** [comment]
@jespejoh Thanks for your solution

**Comment by cesg** [comment]
I solved it configuring trusted proxies
[docs](https://laravel.com/docs/8.x/requests#configuring-trusted-proxies)

**Comment by AlexR1712** [comment]
@cesg yes, if you are having this issue when you are deploying your application via Docker in my case using Dokku
You need to define all the trusted proxies in order to avoid this problem because your application is being forwarded traffic from your load balancer/reverse proxy on port 80 and does not know it should generate secure links.


So just edit the middleware _App\Http\Middleware\TrustProxies_ 

In my case 

``` php
<?php

namespace App\Http\Middleware;

use Fideloper\Proxy\TrustProxies as Middleware;
use Illuminate\Http\Request;

class TrustProxies extends Middleware
{
    /**
     * The trusted proxies for this application.
     *
     * @var string|array
     */
    protected $proxies = '*';

    /**
     * The headers that should be used to detect proxies.
     *
     * @var int
     */
    protected $headers = Request::HEADER_X_FORWARDED_FOR | Request::HEADER_X_FORWARDED_HOST | Request::HEADER_X_FORWARDED_PORT | Request::HEADER_X_FORWARDED_PROTO;
}
```

**Comment by bakerkretzmar** [comment]
I haven't used trusted proxies so I didn't realize they could solve this issue, thanks! Closing this since that is definitely the ideal solution here.

**Comment by BroJenuel** [comment]
> 

I think this is the best solution for this for now,,, changing the proxies to '*' can become a problem in the long run.

**Comment by bakerkretzmar** [comment]
Yeah setting the trusted proxies to `*` isn't a great idea, you should configure them to the actual proxies that your app trusts if possible, but setting that up properly is a better solution than overriding Ziggy's configs right in a script like that.

Also, if you're going to do it that way, use `config('app.url')`, the `env()` helper should only be used in config files so that you can cache your config in production.

**Comment by psalcedodev** [comment]
If anyone is using Forge and are running into this problem, 
go to your server -> site -> environment -> add the https in the APP_URL

**Comment by bipsBro** [comment]
you need to enforce application to use https instead http. which can be achieve by using `\URL::forceScheme('https');`. 

Add following code block in `app/Providers/AppServiceProvider.php`  this will solve your issue. 

```
  public function boot(): void
    {
        \URL::forceRootUrl(\Config::get('app.url'));
        if (str_contains(\Config::get('app.url'), 'https://')) {
            \URL::forceScheme('https');
        }
    }
```

**Comment by AntonOfTheWoods** [comment]
Is there an official way to deal with this now? Neither `trustproxy` as `*` nor `APP_URL` are getting me `https` URLs and it seems strange to have an `APP_URL` that only some modules actually respect. Or am I missing the point somewhere?

**Comment by bakerkretzmar** [comment]
The solution described above has always been the 'official' way: configuring trusted proxies [according to the Laravel docs](https://laravel.com/docs/10.x/requests#configuring-trusted-proxies).

We use `APP_URL` the same way Laravel itself does—it's not that we're not 'respecting' it, it's that the request URL takes priority for route URL generation. If your URLs are being generated with `http` that usually means your Laravel app is seeing the current request URL as only having `http`.

If you think this is a bug with Ziggy feel free to open a new issue, or if you need help with your setup start a discussion and provide as much detail as possible and we'll see how we can help!

**Comment by AntonOfTheWoods** [comment]
I'm not 100% sure why but I had to set up trustproxy and it is working for that reason. I admit to being relatively new to laravel and spent quite a while finding out about asset_url too. I definitely had to use @bipsBro 's little hack to get Https though, so if that is considered a bug, I'll try and make sure I'm getting the right headers. I am behind ingress-nginx, so that may well be the issue.

**Comment by bakerkretzmar** [comment]
You shouldn't ever need `URL::forceScheme('https')`, that kind of thing should be handled by the web server (e.g. nginx) and if your app configures trusted proxies properly it should persist and work there too for URL generation.

**Comment by khalidmk1** [comment]
this solution worked fine  
protected $proxies = '*';
