### ISSUE TITLE
route().params return TypeError

### ISSUE THREAD

**Issue by eensander** [tighten/ziggy#411]
#### Description

`route().params` throws a TypeError: `Uncaught TypeError: t is undefined`.

Also when given the parameter-key, the same output is produced:

`route().params.graph` throws `Uncaught TypeError: t is undefined`.

NOTE: When using this function in the /dashboard on the same environment, it works flawlessly.

#### Expected behavior

The value of the (given) query parameter should be returned, without an error being thrown.

#### Environment

- **Laravel version**: "laravel/framework": "^8.12",
- **Ziggy version**: "tightenco/ziggy": "^1.0"

**Related routes**:

Routes where it fails:

```php
Route::get('/graph/{graph}', [GraphController::class, 'show']); // view on which the function fails
Route::get('/graph/{graph}/get', [GraphController::class, 'get'])->name('graph.get'); // destination route 
```

Part where it works:
```php
Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'auth'], function ($route) {
    (...)
    Route::get('/graph/{graph}/edit', [GraphController::class, 'edit'])->name('graph.edit'); // view where error is produced
    Route::get('/graph/{graph}/get', [GraphController::class, 'get'])->name('graph.get');
});
```

**`Ziggy.routes`**:

```js
{
  "ignition.healthCheck": {
    "uri": "_ignition/health-check",
    "methods": [
      "GET",
      "HEAD"
    ]
  },
  "ignition.executeSolution": {
    "uri": "_ignition/execute-solution",
    "methods": [
      "POST"
    ]
  },
  "ignition.shareReport": {
    "uri": "_ignition/share-report",
    "methods": [
      "POST"
    ]
  },
  "ignition.scripts": {
    "uri": "_ignition/scripts/{script}",
    "methods": [
      "GET",
      "HEAD"
    ]
  },
  "ignition.styles": {
    "uri": "_ignition/styles/{style}",
    "methods": [
      "GET",
      "HEAD"
    ]
  },
  "dashboard.index": {
    "uri": "dashboard",
    "methods": [
      "GET",
      "HEAD"
    ]
  },
  "dashboard.graph.index": {
    "uri": "dashboard/graph",
    "methods": [
      "GET",
      "HEAD"
    ]
  },
  "dashboard.graph.edit": {
    "uri": "dashboard/graph/{graph}/edit",
    "methods": [
      "GET",
      "HEAD"
    ],
    "bindings": {
      "graph": "id"
    }
  },
  "dashboard.graph.get": {
    "uri": "dashboard/graph/{graph}/get",
    "methods": [
      "GET",
      "HEAD"
    ],
    "bindings": {
      "graph": "id"
    }
  },
  "graph.get": {
    "uri": "graph/{graph}/get",
    "methods": [
      "GET",
      "HEAD"
    ],
    "bindings": {
      "graph": "id"
    }
  },
  }
}
```

**Ziggy call and context**:

In the view as described in the laravel-routes above:

```js
route('graph.get', route().params.graph)
```

**Comment by bakerkretzmar** [comment]
`route().params` only works on named routes, because Ziggy needs to look up the current route definition (to get the named parameters). If you give your first route (`/graph/{graph}`) a name, it should work.

I'm not sure I understand what's happening on the `/graph/{graph}/edit` route—are you also seeing the same error there?

**Comment by eensander** [comment]
Thanks! I did not know that the page from where the route gets called needed to be named too.

And no, I was comparing `/graph/{graph}/edit` to the situation where it went wrong. But it now is obvious that it worked on `edit` since that route was already named, as required.
