### ISSUE TITLE
SYNTAX1002 Thrown in IE11

### ISSUE THREAD

**Issue by andrewskm** [tighten/ziggy#414]
#### Description

In IE11, in versions above 0.9.4 the @routes directive is throwing a **SYNTAX1002** error causing all javascript to crash.
In looking at the error, it seems like it is pointing at the class definition `class T` on line 394 of the index.js file.

In order to get things working, I had to revert back to v0.9.4, which is fine.

#### Expected behavior

No syntax error should be thrown, normal page load.

#### Environment

- **Laravel version**:  8.34
- **Ziggy version**: >=1.0.0

**Related routes**:

All pages where @routes is called

**Ziggy call and context**:

Calling the @routes in the main blade layout file

```html
@routes
```
```js
var url = route('pages.dashboard');
```

**Comment by bakerkretzmar** [comment]
If you need to support IE11 you'll have to polyfill JavaScript features that it doesn't have, like the `find` and `includes` Array methods, `Object.entries()`, etc. Check out [polyfill.io](https://polyfill.io/v3/).

Ziggy's bundle should theoretically be compatible with IE11 but it doesn't include polyfills for JavaScript features.

Can you share a longer snippet of the script the error is coming from so I can try to find it in Ziggy's source?

**Comment by andrewskm** [comment]
With v1.0.5 installed, this is the line it gives when the ziggy/dist/index.js file is minified 
```js
"iso-8859-1"===f&&(a=j(a)),c.indexOf("[]=")>-1&&(a=g(a)?[a]:a),n[s]=m.call(n,s)?o.combine(n[s],a):a}return n}(t,r):t,i=r.plainObjects?Object.create(null):{},u=Object.keys(n),f=0;f<u.length;++f){var s=u[f],a=E(s,n[s],r,"string"==typeof t);i=o.merge(i,a,r)}return o.compact(i)};class T{constructor(t,e,
```
and when the file is non-minified
```js
class T
	{
		constructor(t, e, r)
		{
			var n;
			this.name = t, this.definition = e, this.bindings = null != (n = e.bindings) ? n : {}, this.config = r
		}

		get template()
		{
			return ((this.config.absolute ? this.definition.domain ? '' + this.config.url.match(/^\w+:\/\//)[0] + this.definition.domain + (this.config.port ? ':' + this.config.port : '') : this.config.url : '') + '/' + this.definition.uri).replace(/\/+$/, '')
		}
```

Doing some research, looks like the class declaration isn't available for IE11 
https://stackoverflow.com/questions/37194202/ie11-gives-script1002-error-when-defining-class-in-javascript

**Comment by bakerkretzmar** [comment]
Ahh yep you're right, I missed that. For IE11 support you'll need to stay on 0.9.4 then.
