### ISSUE TITLE
nested object query params

### ISSUE THREAD

**Issue by vortechron** [tighten/ziggy#419]
im currently using https://spatie.be/docs/laravel-query-builder , it would be nice if it support something like this http://site.test/admin/users?filter[id]=1&filter[ref]=31"

my workaround:
```
filter.forEach((filterValue, index) => {
    filterString = filterString + `&filter[${filterValue[0]}]=${filterValue[1]}`
})

this.$inertia.replace(this.route(
    'users.index', 
    {
        q: query,
    }
) + filterString)
````

**Comment by vortechron** [comment]
nevermind, got it `route('users.index', {_query: {filter: {id: 'test', haha:'asda', awesome: 'asdad'}}})` haha

**Comment by DevMakoto** [comment]
I have tried to use the route().current('users.index', {_query: {filter: {id: 'test', haha:'asda', awesome: 'asdad'}}}) and it does not work for me

**Comment by bakerkretzmar** [comment]
@DevMakoto you're calling `route().current(...)`, the example in this issue is just `route(...)`.

**Comment by DevMakoto** [comment]
@bakerkretzmar What I want is to check if it is in said route with those parameters, but it doesn't work

**Comment by bakerkretzmar** [comment]
What exact code are you calling, what is the full exact URL of the page at that moment, and what result are you getting/expecting?
