### ISSUE TITLE
Translated Routes

### ISSUE THREAD

**Issue by Manviel** [tighten/ziggy#425]
#### Description

How can I handle routes for different languages?
For example i want to translate: /support
EN: 'support'
FR: 'aide'
And when i am trying to switch from EN to FR i got 404, because page not exist for current locale. Do you have any ideas?
I am using https://github.com/mcamara/laravel-localization
Thanks in advance

**Comment by Manviel** [comment]
Fixed using LaravelLocalization::getURLFromRouteNameTranslated. Issue can be closed

**Comment by bajki** [comment]
Where did you put this?

Can you explain little more because?

**Comment by robertosanval** [comment]
> Fixed using LaravelLocalization::getURLFromRouteNameTranslated. Issue can be closed

Can you please explain how did you solve it? Thanks

**Comment by MammutAlex** [comment]
> Can you please explain how did you solve it? Thanks

Could you kindly clarify the process you used to solve it? Thank you.
