### ISSUE TITLE
TypeError when getting route params of nested page URI

### ISSUE THREAD

**Issue by albertpratomo** [tighten/ziggy#428]
### Ziggy version

v1.2.0

### Laravel version

v8.44.0

### Description

I have a route
```
Route::get('{page}', [PageController::class, 'show'])->name('pages.show');
```

Then when I go to `/nested/pages`, I can see the correct view being rendered.

However, `route().current()` is returning `undefined`, instead of `'pages.show'` that is expected.

Also `route().params` is throwing error:
![image](https://user-images.githubusercontent.com/25815584/120331995-9acc0900-c2ee-11eb-99ab-69f263c73fc2.png)

I believe this has something to do with the URI of the page being nested (`/nested/pages`). If I go to `/not-nested`, everything is working fine.

### Ziggy call and context

```js
route().current();

route().params
```

### Ziggy configuration

```js
port: 8000,
routes: {
  pages.show: {
    methods: (2) ["GET", "HEAD"]
    uri: "{page}"
  },
},
url: "http://localhost:3000",
```

### Route definition

```php
Route::get('{page}', [PageController::class, 'show'])->name('pages.show');
```

**Comment by bakerkretzmar** [comment]
Is that your whole route definition? Is it inside a group or have you added `->where('page', '.*')` anywhere?

By default Laravel allows any character _except_ `/` in route segments, so if you haven't explicitly allowed slashes it should treat `/nested/page` as `{page}/{nextParam}`.
