### ISSUE TITLE
Full SSR support

### ISSUE THREAD

**Issue by jaulz** [tighten/ziggy#431]
#### Description

The library still uses `window` in some places and thus SSR will fail. 

#### Suggestion

Maybe we can add a `getLocation` option to the config that will return `window.location` by default. Having that one could easily pass a static location to Ziggy while using SSR and thus it wouldn't fail.

#### Alternatives

n/a

**Comment by aarondfrancis** [comment]
I don't think it _requires_ window. 

I've got a full Inertia + SSR demo working with no changes to Ziggy. Basically you need Inertia to pass all the Ziggy config to the SSR function, and then redefine your `route` function to use it.

In PHP, add your routes to the page.
```php
$page['ziggy'] = (new Ziggy)->toArray();
```

In your SSR, pull ziggy off the payload:

```js
import route from 'ziggy';

return await createInertiaApp({
        page: event,
        render: renderToString,
        resolve: (name) => require(`./Pages/${name}`),
        setup({app, props, plugin}) {
            return createSSRApp({
                render: () => h(app, props),
            }).use(plugin).mixin({
                methods: {
                    // Pull the ziggy config off of the event.
                    route: (name, params, absolute, config = event.ziggy) => route(name, params, absolute, config),
                },
            })
        },
    });
```

You'll also need to alias ziggy in your webpack config:

```
const path = require('path')
const mix = require('laravel-mix')

require('laravel-mix-merge-manifest')

mix.webpackConfig({
    resolve: {
        alias: {
            ziggy: path.resolve('vendor/tightenco/ziggy/dist'),
        },
    }
})
```

**Comment by jaulz** [comment]
Yep, thanks but that's more or less clear. However, you cannot use `current()` for example. See https://github.com/tighten/ziggy/blob/147804d5f3e98b897fc1ed15efc2807f1099cf83/src/js/Router.js#L72-L74

So that's why I think a configuration possibility would be fine.

**Comment by aarondfrancis** [comment]
Yeah thats true, `current` doesnt work at the moment

**Comment by jaulz** [comment]
If one of the maintainers agrees, I could raise a PR but without their agreement on the approach I'm reluctant 😉

**Comment by aarondfrancis** [comment]
Yeah ideally the location would come from the config or the window, in that order.

**Comment by aarondfrancis** [comment]
@jaulz here's a workaround for now:

```js
import {createSSRApp, h} from 'vue'
import {renderToString} from '@vue/server-renderer'
import {createInertiaApp} from '@inertiajs/inertia-vue3'
import Router from 'ziggy/Router';

exports.handler = async function (event) {
    return await createInertiaApp({
        page: event,
        render: renderToString,
        resolve: (name) => require(`./Pages/${name}`),
        setup({app, props, plugin}) {
            return createSSRApp({
                render: () => h(app, props),
            }).use(plugin).mixin({
                methods: {
                    // Pull the ziggy config off of the event.
                    route: (name, params, absolute, config = event.ziggy) => {
                        const router = new Router(name, params, absolute, config);

                        let original = router.current;

                        router.current = function (name, params) {
                            global.window = {
                                location: new URL(event.ziggy.url)
                            }

                            let result = original.call(this, name, params);

                            global.window = undefined;

                            return result;
                        }

                        return name ? router.toString() : router;
                    },
                },
            })
        },
    });
}
```

**Comment by bakerkretzmar** [comment]
I'm definitely open to a PR that addresses this! Is it basically just replacing `window` with some kind of `getLocation()` function or is there more to it?

**Comment by aarondfrancis** [comment]
@bakerkretzmar reading it off of the config and then falling back to the window would be great for me!
