### ISSUE TITLE
route.current('..') not updating with inertia.js

### ISSUE THREAD

**Issue by ta369e** [tighten/ziggy#433]
### Ziggy version

^1.0

### Laravel version

^8.38

### Description

It was working fine but lately, I noticed that route.current() not updating on page visits, every time I have to refresh in order to get the right active route

### Ziggy call and context

```js
<li class="mainSidebar__rightListItem" 
:class="{ 'mainSidebar__rightListItem--active': route().current('dashboard*') }"
></li>
```

### Ziggy configuration

```js
embedded in blade view of laravel
```

### Route definition

```php
Route::get('/dashboard', [
    DashboardController::class,
    'index',
])->middleware('auth:web')->name('dashboard');
```

**Comment by ta369e** [comment]
what could prevent ziggy from updating ```route().current()``` value
I used the same implementation in somewhere else and it's working fine
but here it does not, no console errors though

**Comment by bakerkretzmar** [comment]
Can you try moving `route().current('dashboard*')` into a computed property and then accessing that property in your template? My guess would be this has something to do with Inertia only re-rendering some parts of the template during navigation.

**Comment by ta369e** [comment]
I found out why.
 ```route().current('dashboard*')``` was accessed in a child component of the layout, I had to pass ```route().current()``` as property to solve it. @bakerkretzmar

**Comment by madsh93** [comment]
> I found out why. `route().current('dashboard*')` was accessed in a child component of the layout, I had to pass `route().current()` as property to the child component to solve it. @bakerkretzmar

I'm using it in a layout, therefore not able to pass it as a prop. Do you know if it is possible to re-fetch current route again somehow?

**Comment by bakerkretzmar** [comment]
@madsh93 try listening for Inertia's `navigate` event maybe? https://inertiajs.com/events#navigate

**Comment by madsh93** [comment]
> @madsh93 try listening for Inertia's `navigate` event maybe? https://inertiajs.com/events#navigate

Haha funny! I was just doing that and was about to post the solution. Thanks!

**Comment by davidoskay** [comment]
> I found out why. `route().current('dashboard*')` was accessed in a child component of the layout, I had to pass `route().current()` as property to the child component to solve it. @bakerkretzmar

Works only if there is no need to check id inside route. I have sidebar with multiple routes, so passing parameter route()->current() only looks for changes in route name, while I need watching route **name and id** param.


I ended doing, any better option?

Sidebar.vue:
```
...
const props = defineProps({
    routeChanged: Object
});

const myNav = ref([]);
const setRoutes = () => {
    myNav.value = [{
        name: 'Main Page',
        href: '#',
        current: route().current('Main Page')
    }, ];

    usePage().props.value.auth.user.myItems.forEach(function(item) {
        let obj = {
            name: item.name,
            href: route('myRoute', item.id),
            current: route().current('myRoute', item.id)
        };
        myNav.value.push(obj);
    });
}
setRoutes();
watch(() => props.routeChanged, setRoutes);
``` 

Layout.vue:
```
<template>
<Sidebar  :routeChanged="routeChanged">
</template>

<script setup>
import Sidebar from "./Sidebar"; 
import { Inertia } from "@inertiajs/inertia";
import { ref } from "vue";

const routeChanged = ref(0);

Inertia.on('navigate', (event) => {
        routeChanged.value = event.detail.page.url;
    })
</script>
```

Any better options?

**Comment by obenchkroune** [comment]
i think this may help

```
<script>
import { ref } from 'vue';
import { Inertia } from '@inertiajs/inertia';


let navigation = ref([]);
const setNavigation = () => {
    navigation.value = [
        {
            name: 'Dashboard',
            href: route('dashboard'),
            current: route().current('dashboard')
        },
    ]
}

Inertia.on('navigate', () => {
    setNavigation();
});
</script>
<template>
    .....
</template>
```

**Comment by stuartcusackie** [comment]
I have the same problem and I tried passing route().current() to the nested component but it had the same problem.

I am thinking that this is related to my default persistent layout. My navigation is part of the layout and not the page component.

I am using a workaround for the moment.

**Comment by JoaoHamerski** [comment]
I used Pinia as a workaround

Here's my store file:
```
import { defineStore } from 'pinia'

export const useAppStore = defineStore('app', {
    state: () => ({
        route: route(),
    }),
    actions: {
        setCurrentRoute () {
            this.route = route()
        }
    }
})
```

Listen to "navigate" event in your main file (my case the main layout), every time the event triggers, call of setCurrentRoute action:
```
router.on('navigate', () => {
  app.setCurrentRoute()
})
```

Use like that in your components: 
```
import { useAppStore } from '@/pinia/app'

const app = useAppStore()

const current = computed(() => {
  return app.route.current()
})
```

**Comment by aqordeon** [comment]
Yes, Pinia help me work around, and works well. Just save the route name whenever the page is changing `router.on('navigate', () => {... pinia method here ...})`
