### ISSUE TITLE
Uncaught TypeError: Cannot read property 'domain' of undefined - with Ngrok

### ISSUE THREAD

**Issue by jjjrmy** [tighten/ziggy#434]
### Ziggy version

v1.2.0

### Laravel version

v8.45.1

### Description

When sharing a local domain with Ngrok.io the routes do not work.
`Uncaught TypeError: Cannot read property 'domain' of undefined`

### Ziggy call and context

```js
submit() {
    this.form.post(this.route('sign', route().params), { preserveState: false })
}
```

### Ziggy configuration

```js
{
defaults: {}
port: null
routes: {ignition.healthCheck: {…}, ignition.executeSolution: {…}, ignition.shareReport: {…}, ignition.scripts: {…}, ignition.styles: {…}, …}
url: "http://myrtr.test"
}
```

### Route definition

```php
Route::post('s/{document}',[DocumentController::class, 'update'])->middleware(['web'])->name('sign');
```

**Comment by bakerkretzmar** [comment]
Can you share the complete section of the config object at `routes.sign`, the complete URL when that error happens, and the value returned from `route().params` on that page? Thanks.

**Comment by jjjrmy** [comment]
> Can you share the complete section of the config object at `routes.sign`, the complete URL when that error happens, and the value returned from `route().params` on that page? Thanks.

```js
routes.sign: {
    bindings: {document: "id"}
    methods: (2) ["GET", "HEAD"]
    uri: "s/{document}"
}
```

`route().params` just returns the document ID

**Comment by bakerkretzmar** [comment]
And the complete URL of the page?

**Comment by jjjrmy** [comment]
> And the complete URL of the page?

The url is `myrtr.test/s/<id>` and I'm trying to post to the same url by using that `this.form.post(this.route('sign', route().params), { preserveState: false })`

**Comment by bakerkretzmar** [comment]
I thought I was able to reproduce this for a few minutes but now I can't anymore. How are you using Ngrok, with `valet share` or another way? Looking at the output you provided again it looks like your app isn't being served through Ngrok, or doesn't know it is—at least not on the pages you got that output from. `Ziggy.url` should be the Ngrok URL.
