### ISSUE TITLE
when use route helper function in Vue component methods , `route` don't work.

### ISSUE THREAD

**Issue by marol1210** [tighten/ziggy#435]
### Ziggy version

v1.2.0

### Laravel version

8.46.0

### Description

1. composer require tightenco/ziggy:1.2.0  
2. php artisan ziggy:generate 
3. app.js

> import { ZiggyVue } from 'vendor/tightenco/ziggy/dist/vue'
> import { Ziggy } from 'resources/js/ziggy'
> 
> let app = createApp({....})
> app.use(ZiggyVue, Ziggy)

4. in a Vue's component

> export default {
> 	name: "Header",
> 	computed:{
> 		layout:function(){
> 			return 'Layout';
> 		}
> 	},
> 	methods:{
> 	   logout:function(){
> 	       this.$inertia.post(route('logout'))
> 	   }
> 	}
> }

result:
route is not defined

### Ziggy call and context

```js
in a Vue's component:
export default {
	name: "Header",
	computed:{
		layout:function(){
			return 'Layout';
		}
	},
	methods:{
	   logout:function(){
	       this.$inertia.post(route('logout'))
	   }
	}
}

result:
route is not defined
```

### Ziggy configuration

```js
const Ziggy = {"url":"http:\/\/localhost:8800","port":8800,"defaults":{},"routes":{"logout":{"uri":"admin\/logout","methods":["POST"]}}};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    for (let name in window.Ziggy.routes) {
        Ziggy.routes[name] = window.Ziggy.routes[name];
    }
}

export { Ziggy };
```

### Route definition

```php
Route::post('logout', [LoginController::class, 'logout'])->name('logout');
```
![image](https://user-images.githubusercontent.com/7519301/122535478-30d59280-d056-11eb-9183-092710324a5c.png)

**Comment by bakerkretzmar** [comment]
In your templates you can use the `route()` function directly, but inside the Vue component's `<script>` tags you have to reference it as `this.route()`. It basically just gets mixed in as a method on every component.

```diff
methods:{
  logout:function(){
-   this.$inertia.post(route('logout'))
+   this.$inertia.post(this.route('logout'))
  }
}
```
