### ISSUE TITLE
The package uses ES6 syntax, which causes compatibility issue with older browsers

### ISSUE THREAD

**Issue by francoislevesque** [tighten/ziggy#440]
### Ziggy version

v1.3.1

### Laravel version

v.8.47

## Current Setup

I'm using Ziggy the "regular" way with `@route` in the main blade file.
Ziggy works fine on modern browsers.

## Issue
On chrome 79, the Nullish coalescing operator "??" is not supported. However, the `@route` macro uses it.

Excerpt:
`{...}this.name=t,this.definition=e,this.bindings=e.bindings??{},this.config=r{...}`

Ideally, the javascript code should not use ES6 syntax for better compatibility.

## Question
Is this an issue with my current setup? Or is this an issue with the package itself?

### Ziggy call and context

```js
route('login')
```

### Ziggy configuration

```js
{
  url: "https://luminaire-authentik-erp.test", 
  port: null, 
  defaults: {…}, 
  routes: {…}
}
```

### Route definition

```php
Route::get('login')->name('login');
```

**Comment by bakerkretzmar** [comment]
Thanks! I didn't realize that our `defaults, not IE 11` Babel target is actually supporting _less_ that if we didn't have anything there, so I'll remove it.
