### ISSUE TITLE
Swoole server not load ziggy-js, Ziggy is not defined error appears.

### ISSUE THREAD

**Issue by medyun** [tighten/ziggy#443]
### Ziggy version

1.3.4

### Laravel version

5.7.29

### Description

I'm trying to run my project with swoole, but I'm getting an error in ziggy js. It works fine for the first couple of requests, but then it starts giving the following error.

![image](https://user-images.githubusercontent.com/423219/125433138-36ca9219-c468-47cb-b4f0-61ad8a0b37e4.png)

### Ziggy call and context

```js
I added @routes declaration into blade.php
```

### Ziggy configuration

```js
When i run console.log(Ziggy), error "Uncaught ReferenceError: Ziggy is not defined" appears.
```

### Route definition

```php
The error is not related to the route definitions.
```

**Comment by bakerkretzmar** [comment]
Are you using Octane?

**Comment by bakerkretzmar** [comment]
Ah never mind, just saw you're on Laravel 5.7. You'll need to reset the internal 'generated' state at the beginning of each request. Take a look at #415 to see how we're doing that for Octane—it should be as simple as `BladeRouteGenerator::$generated = false;` at the very beginning of each new request cycle. Let me know if that works for you!
