### ISSUE TITLE
Can't use vue plugin with vite

### ISSUE THREAD

**Issue by atymic** [tighten/ziggy#447]
### Ziggy version

1.3.5

### Laravel version

8.52

### Description

Aliasing `ziggy` to `vendor/tightenco/ziggy/dist/vue` or `vendor/tightenco/ziggy/dist` doesn't allow es module import.

Just posting this in case anyone else has this issue, managed to get it imported using below code. Using the alias didn't work.

### Ziggy call and context

```js
import { ZiggyVue } from '../../vendor/tightenco/ziggy/dist/vue.m.js';
import { Ziggy } from '../js/ziggy.js';

createApp().use(ZiggyVue, Ziggy)
```

### Ziggy configuration

```js
N/A
```

### Route definition

```php
N/A
```

**Comment by bakerkretzmar** [comment]
Can you share your `vite.config.js`?

**Comment by Spice-King** [comment]
@atymic You need to toss Ziggy to the optimizer too, like so:
```typescript
import { defineConfig } from "vite";

export default defineConfig({
  resolve: {
    alias: {
      ziggy: "vendor/tightenco/ziggy/dist/vue",
    },
  },

  optimizeDeps: {
    include: ["ziggy"],
  },
});
```

Probably worth a note for the docs.

**Comment by atymic** [comment]
hmm, I still get a 404 error when trying that.

**Comment by bakerkretzmar** [comment]
@atymic what if you alias directly to one of the files that uses ES modules? `vendor/tightenco/ziggy/dist/vue.es.js` or `vendor/tightenco/ziggy/dist/vue.m.js`?

**Comment by Spice-King** [comment]
You'd need to restart Vite for optimizeDeps to take effect, but it did work for me in Vite 2.3.8 as is. Not that it really helps with Vue 3 and the composition API.
