### ISSUE TITLE
Emphasis on security implications/risks of this package in readme

### ISSUE THREAD

**Issue by AlexJump24** [tighten/ziggy#476]
Hi,

First of all great work on the package, it makes building SPA applications so much easier and its no surprise why its so popular.

However I just wanted to raise a concern regarding a consistent issue I keep coming across. When taking over existing projects quite a few times now this package has been used where all the routes of an application have been exposed in the HTML even to a logged out user.

This means a bad actor can potentially inspect the HTML and see all of the routes. In certain cases this has been routes that have not been authenticated, leading to a compromised route after a short attack vector.

I suppose my thought here is, is there a better way in the form of documentation in the readme that can detail to the user the impact of just outputting routes in a file such as `app.blade.php` and maybe a suggestion of good practice that not all routes are dumped out to a logged out user. 

This has been particularly common in InertiaJS projects which use this package where the developer potentially doesn't fully understand how the routes are made available, although this doesn't really fall under Ziggys concern.

**Comment by muarachmann** [comment]
@AlexJump24 while your point is good, however it is for the developer to architect their projects. The doc makes mentioned of grouping routes.
```
 'groups' => [
        'not_auth' => [
            'app.*',
        ],
       'auth' => [ .... ]
    ],
```
You can use this to your advantage and output the routes you want to output. Then put the necessary conditions in your blade file. I use this approach in my projects and one tip to note is to give your routes **prefixes** and  also the **as** parameter when grouping routes.

**Comment by bakerkretzmar** [comment]
@AlexJump24 thanks for bringing this up! I think it's pretty fair to say that app developers are responsible for ensuring their routes are authenticated properly, and it's not Ziggy's fault if they leave sensitive routes unauthenticated, but you're right that this behaviour is worth mentioning in our documentation just in case it's unexpected and can help someone out. I added a note about this to the Readme.
