### ISSUE TITLE
route().params missing query data

### ISSUE THREAD

**Issue by benjivm** [tighten/ziggy#477]
### Ziggy version

0.8.1

### Laravel version

8.70.2

### Description

Blade template link:
```php
<a href="{{ route('customers.show', [$contact->company->id, 'contact' => $contact->id]) }}">

// http://example.net/customers/123?contact=456
```

### Ziggy call and context

```js
Vue component:

console.log(route().params);

// { customer: 123 }
```

### Ziggy configuration

```js
//
```

### Route definition

```php
Route::get('customers/{customer}', [CustomerController::class, 'show'])->name('customers.show');
```

**Comment by bakerkretzmar** [comment]
This was added in v1.0 so you'll need to upgrade to get query parameters back with `route().params`. Take a look at [the upgrade guide](https://github.com/tighten/ziggy/blob/main/UPGRADING.md#upgrading-from-09x-to-1x) and feel free to reply again here or open a discussion if you have any questions!
