### ISSUE TITLE
Routing breaks when using Mail façade from Laravel with inertia

### ISSUE THREAD

**Issue by Loown** [tighten/ziggy#478]
### Ziggy version

1.4.0

### Laravel version

8.65

### Description

> ### Versions:
> * `@inertiajs/inertia` version: ^0.10.0
> * `@inertiajs/inertia-vue3` version: ^0.5.1
> 
> ### Describe the problem:
> I'm using it with Laravel, if I want to send a mail using Mail façade, I get a strange routing error.
> 
> `Uncaught ReferenceError: Ziggy is not defined` `Uncaught (in promise) ReferenceError: route is not defined`
> 
> ### Steps to reproduce:
> 1. Create a controller that renders a view.
> 2. Mail someone.

### Ziggy call and context

```js
On page load
```

### Ziggy configuration

```js
defaults: {}
port: 8050
routes:
ignition.executeSolution: {uri: '_ignition/execute-solution', methods: Array(1)}
ignition.healthCheck: {uri: '_ignition/health-check', methods: Array(2)}
ignition.scripts: {uri: '_ignition/scripts/{script}', methods: Array(2)}
ignition.shareReport: {uri: '_ignition/share-report', methods: Array(1)}
ignition.styles: {uri: '_ignition/styles/{style}', methods: Array(2)}
success:
methods: Array(2)
0: "GET"
1: "HEAD"
length: 2
[[Prototype]]: Array(0)
uri: "success"
[[Prototype]]: Object
telescope: {uri: 'telescope/{view?}', methods: Array(2)}
[[Prototype]]: Object
url: "http://localhost:8050"
[[Prototype]]: Object
```

### Route definition

```php
Route::get('/success', [SuccessController::class, 'success'])->name('success');
```

**Comment by bakerkretzmar** [comment]
How are you including Ziggy on the page? Are you using the `@routes` Blade directive? Or adding it as some kind of Vue mixin?

**Comment by Loown** [comment]
Hi, thanks for this quick answer, I pretty much have basic inertiaJS implementation with Laravel breeze, this means I have the `@routes` blade directive in my `app.blade.php` file

**Comment by bakerkretzmar** [comment]
Okay, can you provide more detail about your Ziggy setup? Where exactly is the Ziggy call that is causing the error?

This isn't an issue with the `Mail` facade or Inertia, that error message indicates that the `Ziggy` and `route` globals are not being set up properly.
