### ISSUE TITLE
All bindings exposed even if not in path

### ISSUE THREAD

**Issue by jaulz** [tighten/ziggy#480]
### Ziggy version

^1.2

### Laravel version

^8.73

### Description

Right now, Ziggy exposes all bindings of the controller method even if the variable is not part of the path. This is for example the case when a specific parameter is injected via a custom middleware. Hence, the library exposes more information than it is actually necessary. 

My suggestion is to really expose only those parameters that are actually part of the path. Would you accept a PR for this? 

### Ziggy call and context

```js
-
```

### Ziggy configuration

```js
-
```

### Route definition

```php
-
```

**Comment by bakerkretzmar** [comment]
I'm not sure exactly what you mean, can you give an example?

**Comment by jaulz** [comment]
Sure, I have this controller method which has a custom `new` middleware that injects a new instance of the `Team` class. As you can see the path is `/create` only and does not contain the `team` parameter:
```php
  #[
    Post(
      '/create',
      name: 'create',
      middleware: ['new:' . Team::class]
    )
  ]
  public function create(CreateRequest $request, Team $team)
```

However, ziggy generates the following JSON which includes the `team` binding. 
```json
{"api.team.create":{"uri":"/create","methods":["POST"],"domain":"localhost","bindings":{"team":"slug"}}}
```

The client doesn't need to know about it at all because it is not part of the path.

The reason how I stumbled across this is because I created a TypeScript helper function that uses the generated schema and that lets me know which parameter a specific route requires. In this case it tells me that I need to pass the `team` parameter though it's not required at all.

If you think this is not worth to implement, would you maybe be open for a PR that lets me specify how the actual JavaScript file is generated (i.e. https://github.com/tighten/ziggy/blob/main/src/CommandRouteGenerator.php#L38-L52)? Maybe via a custom `Generator` class that can be passed via the configuration?
