### ISSUE TITLE
Running php artisan ziggy:generate on AWS Codebuild fails

### ISSUE THREAD

**Issue by tarishekola** [tighten/ziggy#488]
### Ziggy version

^1.1

### Laravel version

v8

### Description

When I run the ```php artisan ziggy:generate``` command on AWS codebuild, I get the following error, However, when ran locally, it works fine and outputs ' File Generated'

```


[Container] 2021/12/16 08:46:42 Running command php artisan ziggy:generate
--
471 |  
472 | UnexpectedValueException
473 |  
474 | Invalid route action: [C:32:"Opis\Closure\SerializableClosure":243:{a:5:{s:3:"use";a:0:{}s:8:"function";s:77:"function (\Illuminate\Http\Request $request) {
475 | return $request->user();
476 | }";s:5:"scope";s:37:"Illuminate\Routing\RouteFileRegistrar";s:4:"this";N;s:4:"self";s:32:"00000000181a220e000000005ed738b1";}}].
477 |  
478 | at vendor/laravel/framework/src/Illuminate/Routing/RouteAction.php:92
479 | 88▕      */
480 | 89▕     protected static function makeInvokable($action)
481 | 90▕     {
482 | 91▕         if (! method_exists($action, '__invoke')) {
483 | ➜  92▕             throw new UnexpectedValueException("Invalid route action: [{$action}].");
484 | 93▕         }
485 | 94▕
486 | 95▕         return $action.'@__invoke';
487 | 96▕     }
488 |  
489 | +6 vendor frames
490 | 7   [internal]:0
491 | Illuminate\Routing\CompiledRouteCollection::Illuminate\Routing\{closure}()
492 |  
493 | +20 vendor frames
494 | 28  artisan:37
495 | Illuminate\Foundation\Console\Kernel::handle()
496 |  
497 | [Container] 2021/12/16 08:46:42 Command did not exit successfully php artisan ziggy:generate exit status 1
```

### Ziggy call and context

```js
AWS Codebuild
```

### Ziggy configuration

```js
na
```

### Route definition

```php
na
```

**Comment by bakerkretzmar** [comment]
What version of PHP is the build container running? Can you please share the route definition of the closure route that's error refers to?

I have seen something kind of like this before, I think it's an issue with serializing closures.

**Comment by tarishekola** [comment]
Hello there, its using php 7.4

I am not sure by what you meant here sir

```Can you please share the route definition of the closure route that's error refers to?```

**Comment by bakerkretzmar** [comment]
This part of that error message:

```
474 | Invalid route action: [C:32:"Opis\Closure\SerializableClosure":243:{a:5:{s:3:"use";a:0:{}s:8:"function";s:77:"function (\Illuminate\Http\Request $request) {
475 | return $request->user();
476 | }";s:5:"scope";s:37:"Illuminate\Routing\RouteFileRegistrar";s:4:"this";N;s:4:"self";s:32:"00000000181a220e000000005ed738b1";}}].
```

indicates that you have a closure route somewhere, a route that's just a plain PHP function and doesn't point to a controller method or anything. Laravel is serializing it, probably because you're running `php artisan route:cache` somewhere. That might actually be the issue—are you running `php artisan route:cache` before `php artisan ziggy:generate`? If so, run `php artisan ziggy:generate` first.

If that doesn't work, can you share the original route definition that is just a function in one of your route files? Looking at that error message it probably looks something like this:

```php
Route::get('/', function (Request $request) {
    return $request->user();
});
```
