### ISSUE TITLE
ReferenceError: route is not defined

### ISSUE THREAD

**Issue by lucifer-crybaby** [tighten/ziggy#489]
### Ziggy version

v1.4.2

### Laravel version

v8.76.1

### Description

Hello guys i'm using Laravel Jetstream with ziggy, inertia and vue 3. As you know Jetstream comes with ziggy installed and configured out of the box and it works fine but i don't want to expose my routes in the DOM so at least i wanted to import it to my app js.

Things i did:
### 3. Added webpack alias as shown belove

> _webpack.config.js_

```js
const path = require('path');
   module.exports = {
    resolve: {
        alias: {
            '@': path.resolve('resources/js'),
            ziggy: path.resolve('vendor/tightenco/ziggy/dist/vue'),
        },
    },
};
```
> _webpack.mix.js_

```js
mix.js('resources/js/app.js', 'public/js').vue()
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('tailwindcss'),
    ])
    .webpackConfig(require('./webpack.config'));

if (mix.inProduction()) {
    mix.version();
    mix.disableNotifications();
} else {
    mix.browserSync(process.env.APP_URL);
    mix.disableSuccessNotifications();
}
```
### 4. Imported ziggy
>_app.js_
```js
import { createApp, h } from 'vue';
import { createInertiaApp } from '@inertiajs/inertia-vue3';
import { InertiaProgress } from '@inertiajs/progress';

import { ZiggyVue } from 'ziggy';
import { Ziggy } from './ziggy';

const appName = window.document.getElementsByTagName('title')[0]?.innerText || 'laravel';

createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) => require(`./Pages/${name}.vue`),
    setup({ el, app, props, plugin }) {
        return createApp({ render: () => h(app, props) })
            .use(plugin, ZiggyVue, Ziggy)
            .mixin({ methods: { route } })
            .mount(el);
    },
});

```
since i used vue 3 and configured route() globally i can use it everywhere in my vue app right ? 
so i do this in my vue app
```vue
  <NavLink :href="route('login')" :active="route().current('login')">
         Login
  </NavLink>
```

After i did all according to docs it causes
`Uncaught (in promise) ReferenceError: route is not defined`
![error](https://i.ibb.co/30xfR4j/Screenshot-from-2021-12-16-19-35-29.png)

but if i remove `mixin({ methods: { route } })` from `app.js`
it causes
`Uncaught (in promise) TypeError: _ctx.route is not a function`

Sorry from my bad english. Hope someone helps me :slightly_smiling_face:

### Ziggy call and context

```js
/
```

### Ziggy configuration

```js
/
```

### Route definition

```php
/
```

**Comment by bakerkretzmar** [comment]
Each Vue plugin needs its own `.use()` call, and the arguments for `.use()` are the plugin itself first, and then an optional configuration object. Try this in your `app.js`:

```diff
-             .use(plugin, ZiggyVue, Ziggy)
+             .use(plugin)
+             .use(ZiggyVue, Ziggy)
```

**Comment by lucifer-crybaby** [comment]
> Each Vue plugin needs its own `.use()` call, and the arguments for `.use()` are the plugin itself first, and then an optional configuration object. Try this in your `app.js`:
> 
> ```diff
> -             .use(plugin, ZiggyVue, Ziggy)
> +             .use(plugin)
> +             .use(ZiggyVue, Ziggy)
> ```

Still causes Uncaught (in promise) ReferenceError: route is not defined

**Comment by bakerkretzmar** [comment]
Remove `.mixin({ methods: { route } })` too, that's what the `ZiggyVue` plugin does.

**Comment by lucifer-crybaby** [comment]
> Remove `.mixin({ methods: { route } })` too, that's what the `ZiggyVue` plugin does.

Oh it works now! i much appreciate your quick and clear responses. But i think if these things were on the docs it would be much helpful for beginners like me who has no idea what's wrong kkkk. I'm closing this issue now. Thanks again. Keep up the good work.
