### ISSUE TITLE
Route breaks when using optional parameter with custom key

### ISSUE THREAD

**Issue by RSpeekenbrink** [tighten/ziggy#491]
### Ziggy version

v1.4.2

### Laravel version

v8.76.2

### Description

When configuring a route with an optional parameter and custom key Ziggy does not parse this correctly.

Ziggy output:

```
http://localhost/%7Bworld?:slug}?new-world=
```

### Ziggy call and context

```js
// Where slug is slug for world, using InertiaJS
this.$inertia.visit(this.route('index', slug), {
    only: ['world'],
});
```

### Ziggy configuration

```js
{
  url: 'http://localhost',
  routes: {
    index: {uri: '{world?:slug}',methods: ["GET","HEAD"], bindings: {world: "id"}},
  }
}
```

### Route definition

```php
Route::get('/{world?:slug}', [WorldController::class, 'show'])
    ->name('index');
```

**Comment by RSpeekenbrink** [comment]
By changing the config in laravel to

```
Route::get('/{world:slug}', [WorldController::class, 'show'])
    ->name('index');
```
or

```
Route::get('/{world?}', [WorldController::class, 'show'])
    ->name('index');
```

it does work, so its definitely the combination that is currently unsupported.

**Comment by RSpeekenbrink** [comment]
This is my workaround by the way:

Change laravel config to:

```php
Route::get('/', [WorldController::class, 'show'])
    ->name('index');

Route::get('/{world:slug}', [WorldController::class, 'show'])
    ->name('index.slug');
```
Ziggy usage:
```js
if (slug) {
    this.$inertia.visit(this.route('index.slug', slug), {
       only: ['world'],
   });
} else {
   this.$inertia.visit(this.route('index'), {
       only: ['world'],
   });
}
```

**Comment by bakerkretzmar** [comment]
I believe the correct syntax for optional parameters with custom binding keys is actually `{world:slug?}`. Can you try that and see if it works as expected?

See https://github.com/laravel/framework/blob/8.x/src/Illuminate/Routing/RouteUri.php#L34-L61

**Comment by RSpeekenbrink** [comment]
> I believe the correct syntax for optional parameters with custom binding keys is actually `{world:slug?}`. Can you try that and see if it works as expected?
> 
> See https://github.com/laravel/framework/blob/8.x/src/Illuminate/Routing/RouteUri.php#L34-L61

Works as expected indeed. Guess I never actually used this combination correctly :$

Thanks!
