### ISSUE TITLE
route().current is inconsistent with laravel

### ISSUE THREAD

**Issue by Tofandel** [tighten/ziggy#513]
### Ziggy version

v1.4.3

### Laravel version

any

### Description

Go to the `seminars.quote` page and follow the Ziggy call

### Ziggy call and context

```js
console.log(route().params); // logs "devis"
console.log(route().current('seminars.quote', route().params)); // logs false but should be true
```

### Ziggy configuration

```json
{
  "url": "http://127.0.0.1:8000",
  "port": 8000,
  "defaults": {},
  "routes": {
    "seminars": {
      "uri": "colloques/{page?}",
      "methods": [
        "GET",
        "HEAD"
      ],
      "wheres": {
        "page": "[0-9]+"
      }
    },
    "seminars.quote": {
      "uri": "colloques/devis",
      "methods": [
        "GET",
        "HEAD"
      ]
    }
  }
}
```

### Route definition

```php
Route::prefix('colloques')->group(function () {
    Route::get('{page?}', function () {
        return "Seminars";
    })->where('page', '[0-9]+')->name('seminars');

    Route::get('devis', function () {
        return "Seminars quote";
    })->name('seminars.quote');
});
```

### Analysis of the bug

Looking at the [`matchesUrl`](https://github.com/tighten/ziggy/blob/main/src/js/Route.js#L57) method, it looks like it's not using the `wheres` property of the route, but it should validate the found route against it, otherwise it matches the parent route which has an optional parameter

A workaround is to just invert the route definition so that the one without parameter gets matched first

```php
Route::prefix('colloques')->group(function () {
    Route::get('devis', function () {
        return "Seminars quote";
    })->name('seminars.quote');
    
    Route::get('{page?}', function () {
        return "Seminars";
    })->where('page', '[0-9]+')->name('seminars');
});
```

But for more complex scenarios with overlapping params, this will not be possible, in any case the behavior differs from laravel

**Comment by bakerkretzmar** [comment]
Right now Ziggy only uses that `wheres` key to check for wildcards (`*`) to avoid encoding slashes in the last segment when necessary. Ziggy doesn't really support actual `where` constraints on route definitions. That would be useful though, we can look into it (and I'd welcome a PR to add it!).

For now, putting your more specific `devis` route definition first should fix this.

**Comment by Tofandel** [comment]
Yep I just figured the workaround and edited while you where replying

I think there is 2 ways to go here:
1. Either we make the dehydration aware of the routes and validate the dehydration, this would prove very complex and resource intensive
2. Or we remove all this dehydration part and just pass the current route name and parameters in the head of the app (so that it works also in cases where using static generation) and use them in route().params and route().current()

**Comment by Tofandel** [comment]
PR is done with a bunch of tests and it works wonders in my app

**Comment by bakerkretzmar** [comment]
Awesome, I'll take a look this week!
