### ISSUE TITLE
Route with parameters not correct

### ISSUE THREAD

**Issue by patiefariey** [tighten/ziggy#524]
i have setup everything and when i use the route() in the js for routes with n parameters its working great but for those that do have parameters, they are renders incorrectly like

this: route('admin.orders.show',1)
returns: https://office.app/og-admin/orders/%7B%7D?1=

Do you have an idea why that is?

**Comment by bakerkretzmar** [comment]
Can you share more info so I can help debug this please? Ziggy version, how you're integrating it, if you're using Vue or React or something else, an example route definition, your Ziggy configuration, etc. Thanks.

**Comment by patiefariey** [comment]
Hi there,

am using "tightenco/ziggy": "^1.4" on a Laravel installation

Have inserted the @route() in footer before any custom js 

Am using Route::resource('/', OrdersController::class); which includes the admin.orders.show route and an ID as the parameter that can be passed.

Am using vanilla js

**Comment by patiefariey** [comment]
@bakerkretzmar managed to fix the error. My routes were all messed up :)

**Comment by bakerkretzmar** [comment]
Glad you got it sorted! 👍🏻
