### ISSUE TITLE
The route duplicating it self

### ISSUE THREAD

**Issue by sukmaw** [tighten/ziggy#531]
### Ziggy version

v1.4.4

### Laravel version

v8.75

### Description

First the url look right like this
![Screenshot from 2022-03-15 02-08-00](https://user-images.githubusercontent.com/12524835/158244082-91132b21-c851-47c5-aa47-b1064e9f0b0c.png)

But after several second it change and duplicating the url, like this
![Screenshot from 2022-03-15 02-06-16](https://user-images.githubusercontent.com/12524835/158244206-1d995dee-c88e-478b-a074-0c9952ed77b9.png)

after i'm tracing it, i think the problem is on the client side route (Ziggy)

### Ziggy call and context

```js
its default setting with the laravel staterkit
```

### Ziggy configuration

```js
{
    "url": "http://localhost/larainreact",
    "port": null,
    "defaults": {},
    "routes": {
        "ignition.healthCheck": {
            "uri": "_ignition/health-check",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "ignition.executeSolution": {
            "uri": "_ignition/execute-solution",
            "methods": [
                "POST"
            ]
        },
        "ignition.shareReport": {
            "uri": "_ignition/share-report",
            "methods": [
                "POST"
            ]
        },
        "ignition.scripts": {
            "uri": "_ignition/scripts/{script}",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "ignition.styles": {
            "uri": "_ignition/styles/{style}",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "dashboard": {
            "uri": "dashboard",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "register": {
            "uri": "register",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "login": {
            "uri": "login",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "password.request": {
            "uri": "forgot-password",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "password.email": {
            "uri": "forgot-password",
            "methods": [
                "POST"
            ]
        },
        "password.reset": {
            "uri": "reset-password/{token}",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "password.update": {
            "uri": "reset-password",
            "methods": [
                "POST"
            ]
        },
        "verification.notice": {
            "uri": "verify-email",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "verification.verify": {
            "uri": "verify-email/{id}/{hash}",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "verification.send": {
            "uri": "email/verification-notification",
            "methods": [
                "POST"
            ]
        },
        "password.confirm": {
            "uri": "confirm-password",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "logout": {
            "uri": "logout",
            "methods": [
                "POST"
            ]
        }
    }
}
```

### Route definition

```php
Route::get('', function () {
    return Inertia::render('Auth/Login', [
        'canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),
        'laravelVersion' => Application::VERSION,
        'phpVersion' => PHP_VERSION,
    ]);
});
```

**Comment by bakerkretzmar** [comment]
Can you share the actual code that calls the `route()` function?

Is the URL changing all by itself or after a navigation event like clicking something or logging in?

What is your `APP_URL` environment variable set to?

**Comment by sukmaw** [comment]
> Can you share the actual code that calls the `route()` function?
> i think havent's used the `route()` function
> Is the URL changing all by itself or after a navigation event like clicking something or logging in?
> i just hit the index/welcome url
> What is your `APP_URL` environment variable set to?
> i set it to http://localhost/larainreact/

**Comment by sukmaw** [comment]
the base url is `http://localhost/larainreact/`, im serve locally with apache2 with ubuntu 20
i have another project laravel without inertia(react js) and ziggy, but no problem

i didnt see any error message. i use lamp stack with ubuntu

**Comment by sukmaw** [comment]
i was try put the project not in the subfolder (i put directly on /var/www/html/) and the route is fine (no duplicating)

but if i put it on subfolder, it duplicating url..
example: i hit the another url `http://localhost/laraincreat/admin/dashboard` it will duplicating become `http://localhost/laraincreat/admin/dashboard/laraincreat/admin/dashboard`

**Comment by sukmaw** [comment]
HI, after playing around i think the bug is on inertiajs not on the ziggy
first, find the `window.history.pushState` function on app js and unminifying the scripts, and i try debugging it (actual just console log the param)
i found this `public/app.js`
![Screenshot from 2022-03-15 17-54-34](https://user-images.githubusercontent.com/12524835/158362771-db99c1d2-20c9-45f2-a28d-f529c805809c.png)

and here the result of console 

![Screenshot from 2022-03-15 17-55-17](https://user-images.githubusercontent.com/12524835/158362870-bcbb8902-2c6a-431c-9948-90f416f77d5d.png)

and the first comment of that code is the inertiajs

![Screenshot from 2022-03-15 17-56-22](https://user-images.githubusercontent.com/12524835/158363060-366ccfc9-8774-497f-9082-5293a53b6da7.png)

if i see on the `resource/app.js` i think on the createInertiaApp
![Screenshot from 2022-03-15 17-58-52](https://user-images.githubusercontent.com/12524835/158363442-1295a3ad-2405-4f6e-8bef-adca5abeeebe.png)
