### ISSUE TITLE
Get A RegEx Error

### ISSUE THREAD

**Issue by patiefariey** [tighten/ziggy#532]
amd trying to get the parameters using the route().params but i see there is a regex error:

Exception: SyntaxError: Invalid regular expression: /^office.app/og-admin/(?<>[^/?]+)/?$/: Invalid capture group name at new RegExp (<anonymous>) at t.e.matchesU

my url is: https://office.app/og-admin/orders/1314

This was working before now its not.

Can you help

**Comment by bakerkretzmar** [comment]
What browser (app and version) are you seeing that in?

**Comment by patiefariey** [comment]
All of them. It seems its all the routes with parameters. Have tested in Chrome, Edge, FF, Brave, same result

**Comment by bakerkretzmar** [comment]
Can you share the exact code where you're calling `route()` and it triggers that error? Trying to reproduce it now but I can't yet.

**Comment by patiefariey** [comment]
am just running this to get my order_id in my json file

console.log(route());
var order_id = route().params;

**Comment by bakerkretzmar** [comment]
This has to be related to #514 but I can't reproduce it at all. Can you share any other info for debugging? Value of `Ziggy.routes['admin.orders.show']` in the console, the full PHP definition of the route in your routes file, whether it's happening on other routes, etc? Are you using the Blade `@routes` directive? Or generating a `ziggy.js` file?

**Comment by Tofandel** [comment]
The error message indicates there is no parameter name, which shouldn't be possible so it seems your route generation is messed up somehow

Please share how you generate your routes and how you declare them

**Comment by Tofandel** [comment]
@bakerkretzmar Do you see a way parameters could be empty?

If yes a fix is simple

```js
const regex = segment ? `(?<${segment}>${this.wheres[segment]?.replace(/(^\^)|(\$$)/g, '') || '[^/?]+'})` : '[^/?]+';
```

**Comment by patiefariey** [comment]
Its seems it doesnt like route resource controller... well for me that is. As soon as i declared my routes the old fashioned way in Laravel ,then it started working

**Comment by bakerkretzmar** [comment]
@patiefariey can you share the code of the complete route definitions causing this issue, before and after it started working again? Thanks.
