### ISSUE TITLE
Nonce not being added to Ziggy script

### ISSUE THREAD

**Issue by matthewknill** [tighten/ziggy#537]
### Ziggy version

0.8.0

### Laravel version

8.83.5

### Description

I am trying to add a nonce via Spatie's CSP Package, however, it doesn't seem to be added to the Ziggy script. I have tried the following to no avail:

```blade
@routes(false, csp_nonce())
@routes(null, csp_nonce())
@routes(nonce: csp_nonce()) {{-- actually results in an error --}}
```

All result in the following without the nonce:
```html
<script type="text/javascript">
```

### Ziggy call and context

```js
// All
```

### Ziggy configuration

```js
// Don't have nonce so can't run
```

### Route definition

```php
Route::get('login', [AuthenticatedSessionController::class, 'create'])
    ->name('login')
    ->middleware('guest');

// And all other routes
```

**Comment by bakerkretzmar** [comment]
Support for passing in a CSP nonce was added in v0.9.3, those examples should all work after you update.

**Comment by matthewknill** [comment]
Ah my bad, I was using an outdated version. Cheers
