### ISSUE TITLE
Issue with upgrading

### ISSUE THREAD

**Issue by Michael-ka** [tighten/ziggy#544]
### Ziggy version

0.8.1

### Laravel version

6.0

### Description

Updating Laravel and Ziggy breaks the application. I tried to updating laravel 5.5 to 6(before  update to 9) an Ziggy 0.4.1 to 0.8.1(Laravel 6 compatible version).  But this breaks Ziggy functionality, which has worked before.
![Screenshot from 2022-03-28 11-09-53](https://user-images.githubusercontent.com/8157520/160365616-fb4cd4f2-61db-4f77-8bd7-06b8ca1b606a.png)

### Ziggy call and context

```js
import VueRouter from 'vue-router';
import Store from './Store/Store';

Vue.use(VueRouter);

const router = new VueRouter({
  base: '/',
  mode: 'history',
  scrollBehavior(to, from, savedPosition) {
    if (savedPosition) {
      return savedPosition;
    } else {
      return { x: 0, y: 0 };
    }
  },
  linkActiveClass: 'active',
  fallback: false,
});

window.route = (name, params) => {
  return new Router(name, params, false).toString();
};

const addRoute = (authenticated, name, component, meta = {}) => {
  let searching = true;
  let path = '';
  let parameters = {};

  meta.authenticated = authenticated;

  while (searching) {
    try {
      path = route(name, parameters);

      searching = false;
    } catch (exception) {
      const matches = exception.match(/Ziggy Error: \"([^"]+)\" key is required for route/);

      if (matches) {
        parameters[matches[1]] = `:${matches[1]}`;
      } else {
        throw exception;
      }
    }
  }

  if (path) {
    router.addRoute({ path, component, meta });
  }
};

addRoute(false, 'home', () => import('../vue/Home.vue'), { hideMenu: true });
addRoute(false, 'login', () => import('../vue/Auth/Login.vue'), { hideMenu: true });
addRoute(false, 'login.forgot-password', () => import('../vue/Auth/Login.vue'), { hideMenu: true });


export default router;
```

### Ziggy configuration

```js
{
    "namedRoutes": {
     "home": {
            "uri": "/",
            "methods": [
                "GET",
                "HEAD"
            ],
            "domain": "website.test"
        },
        "login": {
            "uri": "inloggen",
            "methods": [
                "GET",
                "HEAD"
            ],
            "domain": "website.test"
        },
        "login.forgot-password": {
            "uri": "inloggen/wachtwoord-vergeten",
            "methods": [
                "GET",
                "HEAD"
            ],
            "domain": "website.test"
        },
    },
    "baseUrl": "https://website..test/",
    "baseProtocol": "https",
    "baseDomain": "website.test",
    "basePort": false,
    "defaultParameters": []
}
```

### Route definition

```php
Route::vue('/', 'home');
Route::vue('inloggen', 'login');
Route::vue('inloggen/wachtwoord-vergeten', 'login.forgot-password');
```

**Comment by bakerkretzmar** [comment]
If you're planning to upgrade to Laravel 9 soon anyway, I would strongly suggest installing the highest Ziggy version you can (which I think should be the latest one) and treating it as a fresh install rather than an upgrade. It'll probably be easier to rewrite the code that uses Ziggy than to upgrade version by version from v0.4.1.

I _think_ that error is because you're using `Router` directly, which is no longer supported. I'm not really sure what your `addRoute` function is doing, but you'll have to use Ziggy's `route()` function directly instead of the `Router` class (you can still wrap it with your own function if you need to. 

I'm going to close this since it isn't an issue with Ziggy but if you have other questions as you're upgrading feel free to reply and I'll help where I can!

**Comment by Michael-ka** [comment]
Hi @bakerkretzmar, thank for your response. I actually did not write the addRoute() method. I was only tasked with upgrading this project to Laravel 9. The addRoute() method uses regex on the exception messages to fill the parameters needed for the routes. I had never seen something like this before.

I had another issue which you maybe able to help me with. I kept getting Cors errors because some API calls used http: instead of https:. I was able to fix it with the solution on this page: https://www.codegrepper.com/code-examples/php/Ziggy+mixed+content+was+loaded+over+https+but+requested+an+insecure+xmlhttprequest+endpoint. I know it's a long shot, but do you have any idea why this "fix" is needed?

**Comment by bakerkretzmar** [comment]
Yeah, see https://github.com/tighten/ziggy/issues/410#issuecomment-814485042. You'll need to configure your app's trusted hosts/proxies. [Docs here.](https://laravel.com/docs/9.x/requests#configuring-trusted-proxies)
