### ISSUE TITLE
Data passed by Ziggy is inside content instead of attributes or json

### ISSUE THREAD

**Issue by TheHandOfKing** [tighten/ziggy#549]
### Ziggy version

1.0

### Laravel version

9.2

### Description

I'm working on a small scale project, let's call it a playground for testing purposes.

I have some data:

      data() {
        return {
          form: this.$inertia.form({
            id: "",
            name: "",
            email: "",
            files: "",
          }),
         };
      }
A form handles the request through a function call on submit:

      this.form
        .transform((data) => ({
          ...data,
          name: this.sample.name,
          email: this.sample.email,
          files: this.sample.files,
        }))
        .patch(
          this.route("cms.products.sample.update", {
            sample: this.sample,
          }),
          {
            forceFormData: true,
            onSuccess: () => {
              this.form.reset();
            },
          }
        );
The sample object that is passed refers to the object that needs to be updated. He is passed correctly and Laravel's dd($sample); reads it properly.

The problem lies in the form data that it is passed. Data is not passed to the $request->all(), that is to the attributes of the request. Rather it is passed to the content part and it is parsed in a very weird way, like this:

#content: """
    ------WebKitFormBoundaryvh1XjftW9MtXqoUC
    Content-Disposition: form-data; name="id"
    
    
    ------WebKitFormBoundaryvh1XjftW9MtXqoUC
    Content-Disposition: form-data; name="name"
    
    Sample Name

Im not sure if it's Ziggy or if anyone anywhere is encountered this, but googling all day led me here. If it turns out it's not an issue on your end just delete it.
    

### Ziggy call and context

```js
this.form
        .transform((data) => ({
          ...data,
          name: this.sample.name,
          email: this.sample.email,
          files: this.sample.files,
        }))
        .patch(
          this.route("cms.products.sample.update", sample),
          {
            forceFormData: true,
            onSuccess: () => {
              this.form.reset();
            },
          }
        );
```

### Ziggy configuration

```js
cms.products.sample.update:
    bindings:
    sample: "id"
    [[Prototype]]: Object
    methods: Array(2)
        0: "PUT"
        1: "PATCH"
    length: 2
    [[Prototype]]: Array(0)
uri: "admin/products/whitelists/{whitelist}"
```

### Route definition

```php
Route::resources([
  'sample' => SampleController::class,
]);
```

**Comment by bakerkretzmar** [comment]
The content looks weird like that because you set `forceFormData: true`, so it's being sent through encoded as `application/x-www-form-urlencoded` or `multipart/form-data`. I'm not sure about the `------WebKitFormBoundaryvh1XjftW9MtXqoUC` thing but the lines after that look normal to me (weird, yes, but normal for a form-encoded submission).

What does `$request->all()` actually dump out for you? What do you see as the request and response in the network tab of your devtools?

Closing because this isn't related to Ziggy but let me know if you have any other questions!

**Comment by TheHandOfKing** [comment]
Even without that attribute i get the same result, request->all() yields an
empty array as well as any other variation. If you have any clue why id be
very thankful

уто, 12. апр 2022. 00:23 Jacob Baker-Kretzmar ***@***.***> је
написао/ла:
