### ISSUE TITLE
CommandRouteGenerator Urls are different from BladeRouteGenerator

### ISSUE THREAD

**Issue by twdnhfr** [tighten/ziggy#550]
Hey,

I am using v1.4.6 and ran into a weird issue today. At first I was wondering why my route('login') would return a "https:" url, which had the effect that I could not login or logout, etc on my local dev system without https.

Then I started digging around what would be the issue because as far as I can see ziggy pretends to use the app.url for route generation. For testing purposes I changed my app.url to xxx.test and it seems this is only reflected in the ziggy.js created by the CommandRouteGenerator. The BladeRouteGenerator in the directive still returns "patdbv2.test" as url and I have no clue where this even comes from, its not present in my .env file, cache is cleared etc. 

![Bildschirmfoto 2022-04-13 um 16 14 57](https://user-images.githubusercontent.com/13796752/163201213-b91b1f15-9140-4319-98b3-e83342401360.png)

Anyone ran into a similar issue? 

Edit:
when I explicitly use the app.url via an the api endpoint like documented it works
`Route::get('ziggy', fn () => response()->json(new Ziggy(null, config('app.url'))));`

just calling the class will revert to something else
`Route::get('ziggy', fn () => response()->json(new Ziggy));`

Edit 2:
it seems the change with app.url was reverted a while ago. So this make a little bit more sense now, but the question remains why does it generate https urls when https is not used / available and why is the result of both generators different?

**Comment by bakerkretzmar** [comment]
The generated JS file and the JS in the browser are different because the console command uses your `APP_URL` environment variable and the Blade directive uses the current request URL.

I'm not sure about the http/https thing though... what is your `APP_URL` and what is the actual full URL in your browser on that page? Are you serving your site with Valet?

**Comment by twdnhfr** [comment]
Thanks for the reply. Yes I am using valet without https for this site and my app url is just "xxx.test" (as shown in the Screenshot) for testing around with this issue, the url in the browser is "http://patdbv2.test". So even the console command is turning my app.url into https.

**Comment by bakerkretzmar** [comment]
Your `APP_URL` environment variable is set to exactly `xxx.test`? If so does setting it to `http://xxx.test` fix this? Run `php artisan view:clear` too and check.

**Comment by twdnhfr** [comment]
Yeah it was set for testing purposes to http://xxx.test. Given patdbv2.test as app_url etc like the default setup its the same:

![ziggyTest](https://user-images.githubusercontent.com/13796752/164047334-5473b617-df15-4d91-bd55-7f0b0e429652.png)

**Comment by bakerkretzmar** [comment]
Sorry just to be super clear—does your `APP_URL` environment variable **include** `http://`? It's a complete, valid URL, not just a domain?

**Comment by twdnhfr** [comment]
yes it is, please have a look at my screenshot, I added everything in there.

**Comment by bakerkretzmar** [comment]
Sorry, completely missed that 🤦🏻 thanks.

**Comment by bakerkretzmar** [comment]
What does `config('app.url')` display if you echo it from that Blade template or run it in Tinker?

**Comment by twdnhfr** [comment]
Basically the same as above:

![Bildschirmfoto 2022-04-20 um 16 20 48](https://user-images.githubusercontent.com/13796752/164252160-6f6f5339-7c06-4656-a3f1-ab61c6035a25.png)

**Comment by coatesjonathan** [comment]
I'm having the exact same problem, I cannot get the URLs to change from HTTP to https when I'm deploying my application to production, even though I have it working as https locally.... but locally I can't change the URL at all either.

**Comment by coatesjonathan** [comment]
Any updates on this? Any ideas how to get ziggy to recognise the correct URL with https?

**Comment by twdnhfr** [comment]
@coatesjonathan as a workaround you could "upgrade" your request to https via the Webserver and leave the urls untouched with http

**Comment by bakerkretzmar** [comment]
I'll spend some time looking into this tomorrow.

@twdnhfr can you share your original screenshot with the app URL and routes Blade directive with one additional line, `url('/')`? Thanks.

**Comment by bakerkretzmar** [comment]
@coatesjonathan in production, are you using any kind of proxy or load balancer? If so you'll need to configure your trusted proxies to get Ziggy to recognize that and use HTTPS, see https://github.com/tighten/ziggy/issues/410#issuecomment-814485042

**Comment by bakerkretzmar** [comment]
@twdnhfr I can't reproduce any part of this locally, any additional info you can provide would be great—any other relevant environment variables or configurations, etc. Other questions I can think of (some of them are basic I know but I'm pretty stumped here):

- Is the entire, exact command you're running to generate the file `php artisan ziggy:generate`?
- Are you setting any `ziggy.*` config values anywhere (in a `config/ziggy.php` file, a service provider, a middleware, etc)?
- What exactly is the `'url'` value being set to in your `config/app.php`?
- Does the issue persist if you restart Valet _and_ clear your route cache, _and_ view cache, _and_ app cache?
- Are you doing anything to the app or request URL in a middleware that could possibly be causing this?
- Do you only see this locally, or in any other environment too? Any other sites?
- Did this start happening after your upgraded to a specific version of Ziggy? If you downgrade does that fix it?

Of course, if you're able to provide an example repo or reproduce this in a fresh site that would be even better 😂
