### ISSUE TITLE
get relative url via mixin

### ISSUE THREAD

**Issue by plweil** [tighten/ziggy#552]
### Ziggy version

1.4.6

### Laravel version

6.20

### Description

I used to be able to generate a relative url via a mixin for a Vue component:

```
export default {
  methods: {
    route: (name, params, absolute = false) => route(name, params, absolute, Ziggy)
  }
}
```

But this no longer works -- at least on a new branch that I am developing. Isn't this the correct way to override `route()` and make the url relative? I don't know whether something changed between versions of Ziggy. I'm at 1.4.6 now. Using Vue 2. I'm not getting an error, but I'm using `route()` to do an axios call in `created()`. This is new, so I'm wondering whether that could be a problem; i.e., the mixin's being ignored if the `route` method is called in `created()`? I've tried changing the method name, but that just seems to break everything.

### Ziggy call and context

```js
const {
        data: {
          users,
          areas,
          counties,
          schools,
          statuses
        }
      } = await axios.get(this.route('api.project_create_data'))
```

### Ziggy configuration

```js
nothing relevant
```

### Route definition

```php
none
```

**Comment by plweil** [comment]
Sure @bakerkretzmar. I've tried so many variations today, but here's what was working on a previous branch. I don't know exactly why I did it this way, but it did work. ;-)

in _bootstrap.js_

```
[....]

// load Ziggy resources for utilizing Laravel named routes in js
import { ZiggyVue } from 'ziggy-js/dist/vue'

window.ZiggyVue = ZiggyVue

import { Ziggy } from '@/ziggy'

window.Ziggy = Ziggy

import ZiggyRoute from '@/components/mixins/ZiggyRoute'

Vue.mixin(ZiggyRoute)

[....]
```

_ZiggyRoute mixin_

```
export default {
  methods: {
    route: (name, params, absolute = false) => route(name, params, absolute, Ziggy)
  }
}
```

app.js

```
[all kinds of other imports]

Vue.use(ZiggyVue, Ziggy)

create: {
this.getCreateData()
}

methods: {
getCreatedata() {
const {
        data: {
          users,
          areas,
          counties,
          schools,
          statuses
        }
      } = await axios.get(this.route('api.project_create_data'))
}
}
```
1. For cypress testing, I use a valet-env.php file for several testing domains
In the current config, the  'APP_URL'  is 'http://widea-editor.test'

2. The url in my generated Ziggy file is 'http://wisconsin-idea.test', which is my "normal" local dev domain.

3. axios.get(this.route('api.project_create_data')) should make a request to 

`http://widea-editor.test/ProjectCreateData`

instead, it makes a request to 
`http://wisconsin-idea.test/ProjectCreateData`, which gives me the wrong set of users to test with.

4. So it seems as if the mixin is being ignored.

5. If I change the name of the method from `route` to `zroute` in the mixin, I get an error that `route is undefined` in the mixin. Which doesn't really make sense to me.

**Comment by plweil** [comment]
To add to the above, if I try to do the same sort of thing from a Pinia store, I get the same result.

Pinia store
```
import route from 'ziggy-js'
import { Ziggy } from '@/ziggy'

window.route = (name, params, absolute = false, config = Ziggy) => route(name, params, absolute, config)

[....]
actions: {
    async loadCreateData() {
      try {
        const {
          data: {
            users,
            areas,
            counties,
            schools,
            statuses
          }
        } = await axios.get(route('api.project_create_data'))
}

```

**Comment by bakerkretzmar** [comment]
Thanks, that's really helpful! A few things:

- your `Vue.mixin(ZiggyRoute)` is probably being overwritten by `Vue.use(ZiggyVue, Ziggy)` because that one gets called later and also registers a mixin method called `route`, my guess is that's why your default `absolute = false` is being ignored (assuming `app.js` is doing `require('./bootstrap.js')` at the top)
- that alone would cause the wrong URL issue you're seeing in tests, but if you wanted to you could also generate a different `ziggy.js` file for testing that has the correct testing URL, and then you could use absolute routes
- not sure what's causing `5.`

Do you have the `ziggy-js` npm package installed or are you aliasing `ziggy-js` in your mix file? Are you also using the Blade `@routes` directive anywhere?

Try this (remove everything else):

```js
// app.js
import route from 'ziggy-js'
import { Ziggy } from '@/ziggy'

Vue.mixin({
  methods: {
    route: (name, params, absolute = false, config = Ziggy) => route(name, params, absolute, config)
  }
})
```

**Comment by plweil** [comment]
Ok, that worked! I wasn't aware of the possible conflict with `Vue.use(ZiggyVue, Ziggy)`. That really helps me understand what's going on here.

I almost went with generating multiple `ziggy.js` files a while back, but ultimately decided that if it worked, using a relative url is "easier" (as long as I get the ziggy setup stuff and the mixin right!).

I am using both the composer and `ziggy-js` packages together. I do not use `@routes` anywhere. I include the artisan generate command as a script in `package.json` to generate the ziggy file either on its own or as part of `npm run dev`.

I still need to check whether the problem persists in the Pinia store file. The only difference is that the mixin is replaced with 

`window.route = (name, params, absolute = false, config = Ziggy) => route(name, params, absolute, config)`

**Comment by bakerkretzmar** [comment]
Okay great! I'll close this now but let me know if you have any other questions. Running `php artisan ziggy:generate` from an npm script as part of your build is a great idea, I don't think I've seen that before but I love it.

You might already know this but you don't need both the npm and composer packages if your whole app is in one repo. You can alias `ziggy` or `ziggy-js` to the compiled javascript files using Mix, there's [an example in our readme](https://github.com/tighten/ziggy#javascript-frameworks). The end result is the same though, the way you're doing it isn't wrong.

I'm not super familiar with Pinia but the only thing there that could be an issue is that the imported route function and your override are both called `route`. If you're running into problems, try something like this:

```js
import baseRoute from 'ziggy-js'
import { Ziggy } from '@/ziggy'

const route = (name, params, absolute = false, config = Ziggy) => baseRoute(name, params, absolute, config)

// now use route() as normal, it will always be your new function and not Ziggy's
```

**Comment by plweil** [comment]
Thanks Jacob!

One thing I’m wondering about: how do you generate the ziggy routes file without the artisan command (which I’m guessing doesn’t exist in the npm package)?

**Comment by bakerkretzmar** [comment]
No problem! You can't, it's part of the composer package. The npm package is basically for apps that have completely separate SPA frontends, potentially in a different repo, but you still need to generate the `ziggy.js` file in the Laravel app and then copy it to the javascript app or load it remotely or something.

**Comment by plweil** [comment]
@bakerkretzmar Just following regarding using Ziggy in Pinia store files.

Here's what works:

```
import route from 'ziggy-js'
import { Ziggy } from '@/ziggy'

const zroute = (name, params, absolute, config = Ziggy) => route(name, params, absolute, config);

and in an action/method:
myconstant = await axios.get(zroute('api.project_create_data'))

```

In other words, the constant has to be something other than "route", and that's what has to be called in a Pinia action. Otherwise webpack will choke on it.

`Identifier 'route' has already been declared.`
