### ISSUE TITLE
UUID pattern route model binding false-positive validation error

### ISSUE THREAD

**Issue by SanderMuller** [tighten/ziggy#556]
### Ziggy version

1.4.6

### Laravel version

8.83.7

### Description

The error:
`Uncaught (in promise) Error: Ziggy error: 'video' parameter does not match required format '\A[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[1-5]{1}[0-9A-Fa-f]{3}-[ABab89]{1}[0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}\z' for route 'video'.`

Can be reproduced with the following details:
https://regex101.com/r/h6QSQu/1

Has matches for PHP but not for ECMAScript, so I think the issue is that this pattern cannot be copied 1-on-1 from PHP to JS.

The route pattern is defined using `app(\Ramsey\Uuid\Rfc4122\Validator::class)->getPattern()`

### Ziggy call and context

```js
//this.video.uuid contains for example: 112ccece-5aa8-432a-8e8b-4f70bac3345a
route('video', {video: this.video.uuid})
```

### Ziggy configuration

```js
var Ziggy = {
    namedRoutes: {
        "video": {"uri": "video\/{video}", "methods": ["GET", "HEAD"], "domain": "video.test"},
    },
    baseUrl: 'https://video.test/',
    baseProtocol: 'https',
    baseDomain: 'video.test',
    basePort: false,
    defaultParameters: []
};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    for (var name in window.Ziggy.namedRoutes) {
        Ziggy.namedRoutes[name] = window.Ziggy.namedRoutes[name];
    }
}

export {
    Ziggy
}
```

### Route definition

```php
Route::get('video/{video}', VideoController::class)->name('video');

// plus in RouteServiceProvider:
Route::pattern('video', app(\Ramsey\Uuid\Rfc4122\Validator::class)->getPattern());
```

**Comment by bakerkretzmar** [comment]
Is that your complete current Ziggy configuration? It's using v0.9.x property names and there are no `wheres` for the route causing this error.

This is coming from the anchors for the beginning and end of the string, if you replace `\A` with `^` and `\z` with `$` it works. You'll have to do this manually for now. Note that they are not _exactly_ the same—`\A` and `\z` match the very beginning and end of the string, while `^` and `$` match the beginning and end of the first _line_, so a valid string followed by a newline and more characters may still pass validation.

I'll think about the best way to solve this. I doubt we can reliably 'translate' regular expressions from PHP to JS, so I'll probably end up putting parameter validation like this behind a flag or something.

**Comment by SanderMuller** [comment]
My bad, I think the Ziggy config was still from before the upgrade.

This is the config file after the update:
```
const Ziggy = {
    "url": "https:\/\/video.test", "port": null, "defaults": {},
    "routes": {
        "dashboard.enrich": {
            "uri": "video\/{video}",
            "methods": ["GET", "HEAD"],
            "wheres": {
                "id": "[0-9]+",
                "video": "\\A[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[1-5]{1}[0-9A-Fa-f]{3}-[ABab89]{1}[0-9A-Fa-f]{3}-[0-9A-Fa-f]{12}\\z",
                "video_id": "[0-9]+"
            },
            "domain": "video.test",
            "bindings": {"video": "uuid"}
        },
    }
};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}

export { Ziggy };
```

I removed the other routes, because we have 100s of routes.

> This is coming from the anchors for the beginning and end of the string, if you replace \A with ^ and \z with $ it works. You'll have to do this manually for now. Note that they are not exactly the same—\A and \z match the very beginning and end of the string, while ^ and $ match the beginning and end of the first line, so a valid string followed by a newline and more characters may still pass validation.

We run `@php artisan ziggy:generate ./resources/assets/js/ziggy.js` as part of composer install in our project, so I can't manually update the file, it will be regenerated via CI/CD.

Is there any other way to override the route pattern for Ziggy?

Thanks for your help!

**Comment by bakerkretzmar** [comment]
Ahh yeah that config looks better, thanks 😄 

Two ways I can thing of that you could replace the pattern: change it in your route definition, in your PHP routes file (either by just pasting in the whole pattern manually and adjusting it, or by calling `str_replace` or something on the output of the Ramsey package call), or write a small script to update the generated `ziggy.js` file after the build, basically doing the same thing and just replacing those parts of the regex pattern.

Both very annoying and not ideal, I know. I'll work on a better permanent fix.

**Comment by SanderMuller** [comment]
We implemented a temp workaround, extending `CommandRouteGenerator` and  `BladeRouteGenerator` to updated the route patterns before the ziggy file is generated, without affecting the patterns in the actual application.

Before route generation we run this:
```
foreach (app('router')->getRoutes()->getRoutesByName() as $route) {
    $route->wheres = collect($route->wheres)
        ->mapWithKeys(function (string $pattern, string $key) {
            $pattern = Str::of($pattern)
                ->whenStartsWith('\A', fn (Stringable $val): Stringable => $val->replaceFirst('\A', '^'))
                ->whenEndsWith('\z', fn (Stringable $val): Stringable => $val->replaceFirst('\z', '$'))
                ->__toString();
            return [$key => $pattern];
        })
        ->toArray();
}
```

**Comment by bakerkretzmar** [comment]
I think the cleanest way to make this work is actually just to use a compatible Regex pattern. I don't want to mess with replacing tokens in the Regex, it feels really risky and unnecessary. I'd just say if you're using Ziggy, you have to use route patterns that work in JavaScript too.

I dug into this some more and Laravel actually compiles routes into Symfony `CompiledRoute` instances before attempting to match them, and as part of that process the route pattern is transformed into a Regex that matches the entire path. `\A`, `\z, `^`, and `$` are all actually stripped out, and don't appear in the pattern used to match the route—so if you want to keep using your/Ramsey's pattern, you can safely remove those tokens from _all_ UUID route parameters in your entire app, since they were already being ignored (both in route matching during requests and when using Laravel's `route()` helper).

Laravel 9, which has [built-in support for constraining route params](https://laravel.com/docs/9.x/routing#parameters-regular-expression-constraints) based on a pattern, [uses this Regex for UUIDs](https://github.com/laravel/framework/blob/78cb588f9f391016632b3f96755c851a712a442f/src/Illuminate/Routing/CreatesRegularExpressionRouteConstraints.php#L48-L51), which works in JS too:

```regex
[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}
```

So if you're able to, using `whereUuid('video')` might be easiest.
