### ISSUE TITLE
When separating parameters with '-' dash, one of the parameters is not available.

### ISSUE THREAD

**Issue by bitserve-jelle** [tighten/ziggy#557]
### Ziggy version

v1.4.3

### Laravel version

v8.83.4

### Description

I have a route with multiple parameters like this. Within the controller I have both the `year` and `period` parameters available. However, in JavaScript I get all parameters except  the `year` parameter. The `period` and `year` parameters seem to be merged.

![afbeelding](https://user-images.githubusercontent.com/72093340/166668254-1270be10-2f7f-4d59-91f1-ca7dd3ade945.png)

I get the following error:
```
Uncaught (in promise) Error: Ziggy error: 'year' parameter is required for route 'practice-exam'.
```

### Ziggy call and context

```js
// route-helper.js
export default {
    methods: {
        route(...params) {
            return window.route(...params);
        },
    },
}

// Call
const routeName = this.route().current();
const params = this.route().params;

// ...

const url = this.route(routeName, params);
```

### Ziggy configuration

```js
{
  "url": "#DOMAIN#",
  "port": null,
  "defaults": {},
  "routes": {
    ...
    "practice-exam": {
      "uri": "#SUB#/{level}/{course}/{year}-{period}/{question?}",
      "methods": [
        "GET",
        "HEAD"
      ],
      "wheres": {
        "question": "[0-9]+"
      }
    },
    ...
  },
  "absolute": true
}
```

### Route definition

```php
Route::get('{level}/{course}/{year}-{period}/{question?}', [ExamSessionController::class, 'show'])
    ->whereNumber('question')
    ->name('practice-exam');
```

**Comment by bakerkretzmar** [comment]
What's the window URL when you see this error and what do `this.route().current()` and `this.route().params` output in your example?

**Comment by bakerkretzmar** [comment]
Can't reproduce this with your route definition, it works for me locally.

```php
Route::get('{level}/{course}/{year}-{period}/{question?}', fn ($level, $course, $year, $period, $question = null) => tap(view('welcome'), fn () =>dump([$level, $course, $year, $period, $question])))
    ->whereNumber('question')
    ->name('practice-exam');
```

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/18192441/189504867-f2eb4e76-3315-4278-a9d5-a240db42f913.png">

Feel free to tag me if you have more info and I'll look into this more!
