### ISSUE TITLE
Stringable interface breakes backwards compatibility with Laravel version before 7.0

### ISSUE THREAD

**Issue by dlnsk** [tighten/ziggy#558]
### Ziggy version

v1.4.6

### Laravel version

v5.8

### Description

PHP: 7.3.13
Using Stringable interface makes Laravel before 7.0 being unsupported. Downgrading to 1.4.3 gets ziggy to work.

### Ziggy call and context

```js
$./artisan ziggy:generate
makes
Whoops\Run::handleError("Interface 'Stringable' not found", "/var/www/passport/vendor/tightenco/ziggy/src/Output/File.php")
```

### Ziggy configuration

```js
Without configuration
```

### Route definition

```php
No need
```

**Comment by bakerkretzmar** [comment]
Thanks. Most versions between 5.5 and 7 actually do work, but you may need to update your dependencies. See https://github.com/tighten/ziggy/actions/runs/2254637719

I'm going to update our version constraint or add a dependency this week to ensure this is polyfilled correctly wherever possible.

**Comment by nhattrung09it** [comment]
@bakerkretzmar excuxe me, I meet the issue with newest version ~1.6.2, 1.6.0 
 ```
{"message":"Interface 'Stringable' not found","context":{"exception":{"class":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Interface 'Stringable' not found","code":1,"file":"/var/app/current/vendor/tightenco/ziggy/src/Output/Script.php:8"}},
```
Could you support this case?
