### ISSUE TITLE
Route::group(['name' => '']) syntax does not work

### ISSUE THREAD

**Issue by XbNz** [tighten/ziggy#561]
### Ziggy version

v1.4.6

### Laravel version

v9.7.0

### Description

Group routes prepended name does not apply. Tried with 'as' and 'name' array keys in route group configuration.

### Ziggy call and context

```js
Blade layout:

@routes
// ...

Vue component: 

'console.log(route('auth.login.store'))'

Error:

'Ziggy error: route 'auth.login.store' is not in the route list.'
```

### Ziggy configuration

```js
routes:
//...
login.create: {uri: 'login', methods: Array(2)}
login.store: {uri: 'login', methods: Array(1)}
```

### Route definition

```php

Route::group(['name' => 'auth.'], function () {
    Route::get('/login', [LoginController::class, 'create'])->name('login.create');
    Route::post('/login', [LoginController::class, 'store'])->name('login.store');
});

```

**Comment by bakerkretzmar** [comment]
Using `as` as the key, if you run `php artisan route:clear` and then `php artisan route:list`, what's the route name in the list?

**Comment by bakerkretzmar** [comment]
I can't reproduce this in a new app, using `as` it correctly prepends `auth.` to those route names in `route:list` and in Ziggy's output.

**Comment by XbNz** [comment]
```bash
 POST       login ........................... auth.login.store › App\Web\Authentication\Controllers\LoginController@store
 GET|HEAD   login ......................... auth.login.create › App\Web\Authentication\Controllers\LoginController@create
```

I wrongly assumed that `name` and `as` are synonymous. Name must be placed in the static call on the route facade. IDE confused me by presenting it as an option; it seems to do nothing when used in the group options array. 

Turned out not to be a Ziggy problem. Solved.
