### ISSUE TITLE
How to redirect to previous route

### ISSUE THREAD

**Issue by Emokores256** [tighten/ziggy#562]
It's frustrating that there is no feature to redirect to the previous route without forcing page refresh? This feature is lacking in Ziggy routes

This is a feature to add so that we can maintain the redirects of SPAs (no page refreshes).

**Comment by bakerkretzmar** [comment]
Ziggy just generates URLs, like Laravel's own `route()` function, it doesn't handle navigation. Whether you want to use a full page refresh or some other method for navigation, forward or back, is completely up to you and will depend on the framework(s) you're using.
