### ISSUE TITLE
Laravel Maintenance mode generates Ziggy ReferenceError

### ISSUE THREAD

**Issue by marvinschroeder** [tighten/ziggy#568]
### Ziggy version

v1.4.6

### Laravel version

v8.38.16

### Description

We were using InertiaJS with Ziggy. In production environment the global Ziggy JS variable is rendered correctly with the Tightenco\Ziggy\Output\Script.php. If we put the application into maintenance mode with artisan down, the script Tightenco\Ziggy\Output\MergeScript.php is used. This results in a JavaScript error like "Uncaught ReferenceError: Ziggy is not defined" since the global Ziggy JS variable is not defined and just Object.assign'ed.

### Ziggy call and context

```js
We are using InertiaJS with Ziggy. The @routes blade directive is placed before the vendor.js and app.js.
```

### Ziggy configuration

```js
...
```

### Route definition

```php
...
```

**Comment by bakerkretzmar** [comment]
Can you share the contents of the Blade template being rendered when you app is in maintenance mode? Where do you see this error?
