### ISSUE TITLE
Fix route model binding to not use controller parameters reflection

### ISSUE THREAD

**Issue by marvinschroeder** [tighten/ziggy#575]
### Ziggy version

v1.4.6

### Laravel version

v9.21.6

### Description

We were using route model binding and got into a problem were the bindings were not recognized by ziggy. So we debugged it and saw that for resolving the bindings the parameters of the underlying controller were used. So this was the controller were the bindings were not included:

```php
class ViewStaticPageController extends Controller
{
    public function __invoke(StaticPage $page, Request $request): Response
    {

    }
}
```

See the named parameter `$page` instead of `$staticPage`. If we change that into the follwing code the bindings were included:

```php
class ViewStaticPageController extends Controller
{
    public function __invoke(StaticPage $staticPage, Request $request): Response
    {

    }
}
```

So in our opinion the bindings should have been included with both parameter namings, since they both contain the StaticPage model, regardless of the naming. 

Maybe model based route binding should really be based on the `Route::model('staticPage', StaticPage::class);` and `StaticPage->getRouteKeyName()` values and not on the `Illuminate\Routing\RouteSignatureParameters` automatic type reflection.

### Ziggy call and context

```js
...
```

### Ziggy configuration

```js
// Bindings not included when controller parameter is named $page:

{"url":"http:\/\/localhost:3000","port":null,"defaults":{},"routes":{
"static-page":{"uri":"infos\/{staticPage}","methods":["GET","HEAD"]}
}}

// Bindings included when controller parameter is named $staticPage:

{"url":"http:\/\/localhost:3000","port":null,"defaults":{},"routes":{
"static-page":{"uri":"infos\/{staticPage}","methods":["GET","HEAD"],"bindings":{"staticPage":"slug"}}
}}
```

### Route definition

```php
class StaticPage extends Model
{
    public function getRouteKeyName(): string
    {
        return 'slug';
    }
}

Route::model('staticPage', StaticPage::class);

Route::group([
    'prefix' => 'infos',
], function (): void {
    Route::get('{staticPage}', [
        'as' => 'static-page',
        'uses' => ViewStaticPageController::class,
    ]);
});
```

**Comment by bakerkretzmar** [comment]
It actually does matter what the controller method parameter is called here—it needs to be `$staticPage`.

Route model binding expects the parameter name (`staticPage`) to match the _variable name_ of the route action. `Route::get('{staticPage}', fn ($staticPage) => '')` and `Route::get('{page}', fn ($page) => '')` are both valid, `Route::get('{staticPage}', fn ($page) => '')` is not. [Docs.](https://laravel.com/docs/9.x/routing#implicit-binding)

Ziggy's behaviour here is confusing but I'm pretty sure it's correct—you don't actually have a `staticPage` binding for that route in the first scenario, _because_ there is no controller method argument variable named `$staticPage`.

Also, put `Request $request` first. Method parameters that are being resolved and injected automatically by the container should always go before 'regular' parameters that may be passed in as plain values. It sometimes works the way you have it, but there are places where Laravel resolves these different 'kinds' of parameters in order, and putting the ones that need to be injected at the end will break. [Docs.](https://laravel.com/docs/9.x/routing#parameters-and-dependency-injection)
