### ISSUE TITLE
Generate route is wrong in rendered HTML

### ISSUE THREAD

**Issue by ggsuha** [tighten/ziggy#589]
I configure my routes like this:
```
Route::get('/', DashboardController::class)->middleware(['auth'])->name('dashboard');
```

I realized that my current page didn't activated the sidebar item.
What makes me wonder is, when I tried to log the `route('dashboard)`, it's showing right value.
![image](https://user-images.githubusercontent.com/25905626/198831496-a6850b8d-db48-4373-8285-b656446ad70a.png)

But when it comes to html rendering, it changed to... http://localhost/dashboard
![image](https://user-images.githubusercontent.com/25905626/198831545-5d83e6e2-b12d-4be6-8013-074e72b6746c.png)

Here is my SidebarMenu.vue:
```
<NavItem :active="route().current('dashboard')">
          <a :href="route('dashboard')" class="nav-link">
            <span class="sidebar-icon">
              <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z"></path>
                <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z"></path>
              </svg>
            </span>
            <span class="sidebar-text">Dashboard</span>
          </a>
        </NavItem>
```

And the NavItem.vue
```
<script setup>
import { computed } from 'vue';

const props = defineProps(['active']);

console.log(props.active, route('dashboard')); // log
const classes = computed(() => props.active
  ? 'nav-item active'
  : 'nav-item'
);
</script>

<template>
  <li :class="classes">
    <slot />
  </li>
</template>

```

**Comment by bakerkretzmar** [comment]
How are you setting up Ziggy? E.g. `@routes` in some Blade, or using the Vue plugin, etc?

**Comment by bakerkretzmar** [comment]
@ggsuha did you figure this out? We need more information to help debug. Thanks.

**Comment by ggsuha** [comment]
@bakerkretzmar Hi, sorry for late reply

I have `ziggy.js` file
```
const Ziggy = {"url":"http:\/\/localhost","port":null,"defaults":{},"routes":{"ignition.healthCheck":{"uri":"_ignition\/health-check","methods":["GET","HEAD"]},"ignition.executeSolution":{"uri":"_ignition\/execute-solution","methods":["POST"]},"ignition.updateConfig":{"uri":"_ignition\/update-config","methods":["POST"]},"dashboard":{"uri":"dashboard","methods":["GET","HEAD"]},"login":{"uri":"login","methods":["GET","HEAD"]},"logout":{"uri":"logout","methods":["POST"]}}};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}

export { Ziggy };
```

and import it on `app.js`
```
import { ZiggyVue } from "ziggy";
import { Ziggy } from "./ziggy";

const appName =
  window.document.getElementsByTagName("title")[0]?.innerText || "Laravel";

createInertiaApp({
  title: (title) => `${title} - ${appName}`,
  resolve: (name) =>
    resolvePageComponent(
      `./Pages/${name}.vue`,
      import.meta.glob("./Pages/**/*.vue")
    ),
  setup({ el, app, props, plugin }) {
    return createApp({ render: () => h(app, props) })
      .use(plugin)
      .use(ZiggyVue, Ziggy)
      .mount(el);
  },
});
```

And this is the `app.blade.php`
```
<head>
<!--  -->
<!-- Scripts -->
    @routes
    @vite(['resources/js/app.js', "resources/js/Pages/{$page['component']}.vue"])
    @inertiaHead
</head>
```

**Comment by ggsuha** [comment]
@bakerkretzmar Thanks, 

I tried with removing `@routes` in blade and add inject to `SidebarMenu.vue` where the function get called, (`NavItem` actually didn't use `route()` function)  but didn't help.

**Comment by bakerkretzmar** [comment]
> I tried with removing `@routes` in blade and add inject to `SidebarMenu.vue` where the function get called, (`NavItem` actually didn't use `route()` function) but didn't help.

You don't need the `inject` if you're using the `route()` function inside your component template, you only need it if you're using it inside the component's `<script>` tags. It's available in all your templates automatically.

> If I use `@routes` in Blade directive and remove `Ziggy` from app.js, it works.

This makes me thing your `ziggy.js` file with your routes was outdated. If you remove `@routes` from your Blade and use `inject`, and re-run `php artisan ziggy:generate`, does that fix it?

**Comment by bakerkretzmar** [comment]
Run `php artisan route:clear` first too just in case something is cached.

**Comment by ggsuha** [comment]
Already tried it before, `php artisan ziggy:generate` didn't change anything on `ziggy.js`, the content still same as before.

* Tried it again got same result

**Comment by bakerkretzmar** [comment]
What does the line for the 'dashboard' route in `php artisan route:list` look like? Do you have any other routes getting registered with the name `dashboard` or a URI of `/` anywhere else that might be interfering with the one having this problem?

Is this app open-source or are you able to reproduce this issue in a fresh Laravel app?

**Comment by bakerkretzmar** [comment]
@ggsuha can you provide any more information here or a repo with a Laravel app that reproduces this issue?

**Comment by ggsuha** [comment]
@bakerkretzmar 
Sorry for late response. 
It was silly mistake from me, `php artisan ziggy:generate` get url from `APP_URL `, but I didn't change it to my current APP_URL and PORT.

Update `APP_URL` and regenerate ziggy config solved the issue.

**Comment by bakerkretzmar** [comment]
No worries, glad you got it figured out!
