### ISSUE TITLE
Possibility to only output routes without library

### ISSUE THREAD

**Issue by emachiels** [tighten/ziggy#590]
#### Description

Since I am using ziggy-js via NPM, I don't need the library to be injected when I use `@routes` in my blade file. This only results in the JS included twice (one inline in my HTML and one in my JS bundle)

#### Suggestion

Feature to only output the part in my HTML that generates the routes to be used in my JS:
```
const Ziggy = {...};
```
#### Alternatives

None I can think of at the moment. 

P.S. I wouldn't mind contributing such a feature myself, but only if the idea is accepted.

**Comment by bakerkretzmar** [comment]
It doesn't really matter if the JS is technically present twice, so you can just ignore it. If you really want to remove it though there are a few ways you could do that:

- Don't use `@routes`, and instead run `php artisan ziggy:generate` to generate a routes file, and import that in your JavaScript.
- Don't use `ziggy-js`, put the `@routes` Blade directive before your main `<script>`, and use the global `route` function from the HTML.
- Create your own Output class and override Ziggy's script output (see #483).

**Comment by emachiels** [comment]
@bakerkretzmar I didn't know about that feature. Isn't it an idea to put that information in the readme to avoid requests like mine? :P
