### ISSUE TITLE
Laravel 9 Breeze vue 3 ssr starter kit + typescript 

### ISSUE THREAD

**Issue by zynth666** [tighten/ziggy#597]
Hi, I'm trying to get typescript working with this starter kit but I'm having trouble getting the typescript definitions for ziggy working.
![image](https://user-images.githubusercontent.com/11150388/204064020-d68372fb-bf1b-43cb-a4e7-1317f6f08be9.png)

I have installed @types/ziggy-js but I'm not sure what to do next.

Any help would be greatly appreciated.

**Comment by bakerkretzmar** [comment]
The `@types/ziggy-js` package is maintained by the community and looks like it might be out of date. It doesn't look like it includes type definitions for `ZiggyVue` at all, so you may have to just tell TypeScript to ignore it for now.
