### ISSUE TITLE
ApiLoggerInterface Issue

### ISSUE THREAD

**Issue by kuldeepBacancy** [tighten/ziggy#601]
Hello,

Laravel version: `"laravel/framework": "^6.18.35"`
I'm using the below 2 packages at the same time:

```
"awt/apilogger": "dev-master"
"tightenco/ziggy": "^1.0"
```
I've added @routes to some blade files which will be used to get all routes in the javascript files. Now I wanted to add some other packages and after installing/removing other packages I'm getting the error in pages where I've added @routes

I tried removing, installing, and updating the package. Also, checked some solutions and tried this one ([Stackoverflow](https://stackoverflow.com/a/70767545)).

The error screenshot is attached. Can I get the solution for the same?

![202667584-b01ab426-6544-4074-8a8f-ac24192ada55](https://user-images.githubusercontent.com/94948991/204567097-7a75f3da-1719-4c53-bd1f-66932549cf93.png)

**Comment by bakerkretzmar** [comment]
This doesn't look related to Ziggy. You said you tried uninstalling Ziggy, do you still see this error without `@routes` and without Ziggy installed?

**Comment by kuldeepBacancy** [comment]
No, After removing `@routes` the error is not showing.

But, I've added the same issue to the [apilogger](https://github.com/aungwinthant/apilogger/issues/45). And I'm sure that the error comes between these 2 packages only.

**Comment by bakerkretzmar** [comment]
Can you share a complete stack trace or any other debugging info? That screenshot looks like there's an error in your `homenew.blade.php` view, can you share that? With the information I have here this still doesn't seem related to Ziggy.

**Comment by kuldeepBacancy** [comment]
1) There is nothing different debugging for this. If I removed the Ziggy, APILogger package it'll work fine. But with these two packages, I'm not able to add any new packages.
2) It's only one type of the defined process before jquery and another js file that requires to get the routes, nothing else.

![image](https://user-images.githubusercontent.com/94948991/205212542-ba04f13e-081a-4b27-89ad-7b302ace9077.png)

**Comment by bakerkretzmar** [comment]
@kuldeepBacancy I'd like to try to help debug this but I need more information. Can you please share a **complete** stack trace? Your original screenshot says the error is on line 19 of `ApiLoggerInterface`—what is on that line?

It looks like that package might be interacting with your routes in some weird way, are there any routes in your application where if you comment out the route completely, this error disappears and the page loads? If so can you share those route definitions?

It would be great if you could share a reproduction repo for this issue, or a link to your app if it's open source.

**Comment by bakerkretzmar** [comment]
The `ApiLoggerInterface` uses union types, which were added in PHP 8.0. Upgrading your PHP version should resolve this issue.
