### ISSUE TITLE
prints the content of config/ziggy.php with php artisan command and on page load

### ISSUE THREAD

**Issue by kashif-ghafoor** [tighten/ziggy#624]
### Ziggy version

v1.5

### Laravel version

v8.69.0

### Description

when I added basic filtering to ziggy config file. it started printing the content of config/ziggy.php to terminal with every php artisan command and when I load the page of which js file I am using route method I see the content of zigg file and then the actual page is rendered. 
there is no information on readme about this. 

![image](https://user-images.githubusercontent.com/58185339/222735804-99827402-7015-482b-8dc2-d10ca65d738d.png)

### Ziggy call and context

```js
fetch((route('admin.businesses.update',{
        business
    })),{
        method: 'POST',
        body: formData
    }).then(console.log('success'))
```

### Ziggy configuration

```js
return [
    'only' => ['admin.businesses.update', 'admin.businesses.edit'],
];
```

### Route definition

```php
Route::get('/admin/businesses/edit/{business}', 'AdminController@businessesEdit')->name('admin.businesses.edit');
Route::patch('/admin/businesses/{business}', 'BusinessController@update')->name('admin.businesses.update');
```

**Comment by bakerkretzmar** [comment]
Add an opening `<?php` to your `config/ziggy.php` file.
