### ISSUE TITLE
Incorrect URL when route includes domain with a port

### ISSUE THREAD

**Issue by kajetan-nobel** [tighten/ziggy#625]
### Ziggy version

1.5

### Laravel version

10.3.1

### Description

When your `APP_URL` contains port and `domain` from route also contains it'll join together.

### Ziggy call and context

```js
window.route('test', { param: '123' })

# Output
http://127.0.0.1:9100:9000/test/123
```

### Ziggy configuration

```js
{
    "url": "http://127.0.0.1:9000",
    "port": 9000,
    "defaults": {},
    "routes": {
        "sanctum.csrf-cookie": {
            "uri": "sanctum/csrf-cookie",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "ignition.healthCheck": {
            "uri": "_ignition/health-check",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "ignition.executeSolution": {
            "uri": "_ignition/execute-solution",
            "methods": [
                "POST"
            ]
        },
        "ignition.updateConfig": {
            "uri": "_ignition/update-config",
            "methods": [
                "POST"
            ]
        },
        "test": {
            "uri": "test/{param}",
            "methods": [
                "GET",
                "HEAD"
            ],
            "domain": "127.0.0.1:9100"
        }
    }
}
```

### Route definition

```php
Route::get('/test/{param}')
    ->name('test')
    ->domain('http://127.0.0.1:9100');
```

**Comment by bakerkretzmar** [comment]
Just so I'm clear, your `APP_URL` is `http://127.0.0.1:9000`?

What is the URL of the page where you're seeing Ziggy output the double port?

How exactly are you generating your Ziggy config and loading it onto the page?

And how does Laravel's PHP `route()` helper behave here—with that route definition and `APP_ENV`, what does `route('test', ['param' => 123])` output?

**Comment by kajetan-nobel** [comment]
> Just so I'm clear, your APP_URL is http://127.0.0.1:9000?

Correct

> What is the URL of the page where you're seeing Ziggy output the double port?

Homepage aka `/` but it refers to every page

> How exactly are you generating your Ziggy config and loading it onto the page?

`@routes` in blade view

> And how does Laravel's PHP route() helper behave here—with that route definition and APP_ENV, what does route('test', ['param' => 123]) output?

Well, never tested that, but it looks like it has the same output as this package.
`http://127.0.0.1:9100:9000/test/123`

**Comment by bakerkretzmar** [comment]
> Homepage aka `/` but it refers to every page

What's the actual full URL in the browser, including the host? I'm wondering because Ziggy (and Laravel) uses the current request URL for most route generation.

What's the behavior you want or were expecting here? This probably isn't helpful but if Laravel outputs the double port, Ziggy will likely continue to do that as well. I'd rather be consistent with Laravel's behavior even if it's wrong. That being said, if there's clearly a better way to handle this it might be worth PRing to Laravel, I'm just not sure exactly what _should_ happen here.

**Comment by bakerkretzmar** [comment]
Closing this because we want to match Laravel's behaviour even if it's weird or wrong, so I don't think there's anything for Ziggy to change here. I'm still interested if you have a specific suggestion here about what should happen instead, so feel free to comment again!
