### ISSUE TITLE
Laravel 10 Release

### ISSUE THREAD

**Issue by cheyner** [tighten/ziggy#626]
Could you create a release for Laravel 10 support?

**Comment by cheyner** [comment]
Oh, whoops, sorry about that.

**Comment by jannejava** [comment]
Thanks for creating this package! I really appreciate it. Is it possible to tag a release with support for Laravel 10? 🙏

**Comment by bakerkretzmar** [comment]
Laravel 10 is already supported.

**Comment by jannejava** [comment]
Yes in the main branch I can see it. But Laravel 10 support is not in a tagged release. The latest 1.5.0 was in September 20. Or am I missing something, correct me if I am wrong?

**Comment by bakerkretzmar** [comment]
Ziggy 1.5.0 supports all versions of Laravel starting at 5.4, including Laravel 10: https://github.com/tighten/ziggy/blob/main/composer.json#L23
