### ISSUE TITLE
Problem with ziggy when route name starts with a number (eg. 404)

### ISSUE THREAD

**Issue by lukaszahorec** [tighten/ziggy#657]
### Ziggy version

v1.6.0

### Laravel version

v9.52.10

### Description

Hello!

There is a problem with ziggy when route name starts with a number eg. 404. 

`Route::fallback(function () {
    return response()->view('pages.page-404', ['notfoundPage' => true], 404);
})->name('404')->middleware('getlocale');
`

If it starts with number, then in Vue Component when I try to get routes, it starts with a "0" route. The object containing routes look like this:

<img width="756" alt="image" src="https://github.com/tighten/ziggy/assets/2042388/38e7480a-d40b-4464-aab7-12890bd6b170">

Then function route().current() on every route return "0".

When I change route name to:
`Route::fallback(function () {
    return response()->view('pages.page-404', ['notfoundPage' => true], 404);
})->name('error.404')->middleware('getlocale');
`

Then It's working as expected.

<img width="769" alt="image" src="https://github.com/tighten/ziggy/assets/2042388/a7c8c709-a8a7-4a0f-a2cc-5b22930785f7">

### Ziggy call and context

```js
Route::fallback(function () {
    return response()->view('pages.page-404', ['notfoundPage' => true], 404);
})->name('404')->middleware('getlocale');
```

### Ziggy configuration

```js
{
    "0": {
        "uri": "{fallbackPlaceholder}",
        "methods": [
            "GET",
            "HEAD"
        ],
        "wheres": {
            "fallbackPlaceholder": ".*"
        }
    }
}
```

### Route definition

```php
Route::fallback(function () {
    return response()->view('pages.page-404', ['notfoundPage' => true], 404);
})->name('error.404')->middleware('getlocale');
```

**Comment by bakerkretzmar** [comment]
Thanks, you're right. Looks like this is coming specifically from the collection`->merge()` method. I'll dig in further on Friday.
