### ISSUE TITLE
Route `/` doesn't work with absolute=false

### ISSUE THREAD

**Issue by mathieutu** [tighten/ziggy#666]
Hi!
Because of the removal of last `/`,  the home (`/`) route link doesn't work with Ziggy.
An update in the regexp should do the work. (I can do it if you want)
https://github.com/tighten/ziggy/blob/f2b43c03e49b0f717168b1d578c8c4f8c423daca/src/js/Route.js#L119-L119

Thanks,
Matt'

**Comment by bakerkretzmar** [comment]
Oh good catch. Yeah if you can PR that (with a test please!) that would be great, thanks. Otherwise I'll do it Friday.
