### ISSUE TITLE
Impossible to use route() in script (Vue3)

### ISSUE THREAD

**Issue by Oui-Dev** [tighten/ziggy#685]
### Ziggy version

1.8.1

### Laravel version

10.28

### Description

I'm using ziggy and it works well in <template> but when i'm using it in <script> (vue 3 composition API) i get this error "Uncaught ReferenceError: route is not defined".

So i tried to "import route from 'ziggy-js';" and i get this error "Uncaught SyntaxError: The requested module '/vendor/tightenco/ziggy/dist/vue.es.js' does not provide an export named 'default'".

This is my configuration :
```
// vite.config.js
resolve: {
	alias: {
                ziggy-js': resolve('vendor/tightenco/ziggy/dist/vue.es'),
         },
},
```
	
```
// app.js
import { ZiggyVue } from 'ziggy-js';
import { Ziggy } from './ziggy';

...

const app = createApp({ render: () => h(App, props) })
     .use(plugin)
     .use(ZiggyVue, Ziggy);

app.config.globalProperties.cc = cc;
app.mount(el);
```

If i put "@routes" in my app.blade.php it work but if i do that i import twice my routes 

### Ziggy call and context

```js
// Using ziggy in <script> (i'm using it with inertia)
form.post(route('login.post'), { onStart: () => form.clearErrors() });
```

### Ziggy configuration

```js
{
    "url": "http://dogger.test",
    "port": null,
    "defaults": {},
    "routes": {
        "sanctum.csrf-cookie": {
            "uri": "sanctum/csrf-cookie",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "ignition.healthCheck": {
            "uri": "_ignition/health-check",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "ignition.executeSolution": {
            "uri": "_ignition/execute-solution",
            "methods": [
                "POST"
            ]
        },
        "ignition.updateConfig": {
            "uri": "_ignition/update-config",
            "methods": [
                "POST"
            ]
        },
        "register": {
            "uri": "register",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "register.post": {
            "uri": "register",
            "methods": [
                "POST"
            ]
        },
        "login": {
            "uri": "login",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "login.post": {
            "uri": "login",
            "methods": [
                "POST"
            ]
        },
        "logout": {
            "uri": "logout",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "homepage": {
            "uri": "/",
            "methods": [
                "GET",
                "HEAD"
            ]
        },
        "dashboard.index": {
            "uri": "dashboard",
            "methods": [
                "GET",
                "HEAD"
            ]
        }
    }
}
```

### Route definition

```php
All routes
```

**Comment by bakerkretzmar** [comment]
Quick fix: use `const route = inject('route');` instead of importing it.

---

The `route` function is exported from Ziggy's root, not from the Vue plugin, which is why your import doesn't work. You'd need to import the Vue plugin from `dist/vue.es` and the `route` function from just `dist`, which would require using 2 different import aliases or the entire file path and no alias. Kind of annoying, but not necessary since the plugin provides `route` for you to inject.

If you don't want to inject _or_ import it everywhere, use the `@routes` Blade directive. This will let you skip running the Artisan command, you can remove `import { Ziggy } from './ziggy';` and update the plugin to just `.use(ZiggyVue)`, and you can add [global type declarations](https://github.com/tighten/ziggy?tab=readme-ov-file#typescript) so your IDE doesn't complain.

**Comment by Oui-Dev** [comment]
Thanks it works !
But what is the best practice, using `@routes` or generating and importing the js file ? What are the pros and the cons ?

**Comment by bakerkretzmar** [comment]
Either one is fine, but I would use `@routes` in Blade. I consider the generated JS file a workaround for when you're working with a backend and frontend that are isolated from each other for some reason, or for when you _can't_ use the Blade directive. `@routes` is simpler and there are fewer steps to use it.

**Comment by Oui-Dev** [comment]
Thank you for the explanations ! I'll consider using "@routes" instead of the JS file :)

**Comment by mrleblanc101** [comment]
Might I suggest that `const route = inject('route');` be added to the README as an exemple ?
As someone who lost many hours trying to solve the same problem.
I initially did something like this:
```js
// ssr.js
globalThis.Ziggy = page.props.ziggy;

// somewhere-else.js
import { route } from 'ziggy-js'
```

**Comment by ctf0** [comment]
@bakerkretzmar could u plz update the rdme with the correct steps as i lost 2 days trying to get it to work just to see your comment.

also for anyone else, if you're using the `@routes` in your blade, you can unset the routes from the inertia shared data ex.`unset((new Ziggy)->toArray()['routes'])`
