### ISSUE TITLE
Class "Tightenco\Ziggy\Ziggy" Not Found After Upgrading to Laravel 11

### ISSUE THREAD

**Issue by omarbouziane** [tighten/ziggy#731]
### Ziggy version

2.0.4

### Laravel version

11.0.6

### Description

Hello,

I recently attempted to upgrade my application to Laravel 11 and encountered a significant issue. Specifically, the "Tightenco\Ziggy\Ziggy" class could not be found, causing my application to break. This issue arises in the context of an application that utilizes Laravel with Inertia.js and Vue.js.

Has anyone else encountered this issue, or does anyone have suggestions on how to resolve it? Any assistance would be greatly appreciated as I am currently unable to proceed with the Laravel 11 upgrade due to this problem.

Thank you!

### Ziggy call and context

```js
E.g.:

<Link :href="route('profile.show')">
<Link :href="route('dashboard')">

and everywhere I use the route helper
```

### Ziggy configuration

```js
HandleInertiaRequests

use Tightenco\Ziggy\Ziggy;

'ziggy' => function () use ($request) {
    return array_merge((new Ziggy)->toArray(), [
        'location' => $request->url(),
    ]);
},
```

app.js

```
import { ZiggyVue } from '../../vendor/tightenco/ziggy/dist/vue.m';

// Usage with Vue
.use(ZiggyVue)
```

In app.blade.php, I include the @routes.

### Route definition

```
Route::get('/profile', [ProfileController::class, 'show'])->name('profile.show');
```

**Comment by bakerkretzmar** [comment]
As noted in the [upgrade guide](https://github.com/tighten/ziggy/blob/2.x/UPGRADING.md#upgrading-from-1x-to-2x), Ziggy's PHP namespace changed from `Tightenco` to just `Tighten` in v2. It would be helpful if you included more context about the specific error you're seeing (including a stack trace) and where it's coming from, but if you're using that class anywhere make sure to update your imports.

**Comment by andrewRybachuk** [comment]
It's a cache issue. All you need is to restart your web server and clear the application cache.
