### ISSUE TITLE
Vu3 Composition api 

### ISSUE THREAD

**Issue by hasanablak** [tighten/ziggy#768]
Can we add any example inside to docs for usage when we use vue3 composition api?

I'am using like that;

import { useRoute } from 'ziggy-js';
import { Ziggy } from '../ziggy';

...

const route = useRoute(Ziggy);

...

async function abc(){
	await axios.get(route('api.notification.count'))
}

**Comment by mhelaiwa** [comment]
You should use vue 3 `inject`. I've created a PR #785 to note that inside the docs
